package winze

// Metabolism cycle 3: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Each is backed by a Conjecture (winze's own generation, never a source).

// ---------------------------------------------------------------------------
// Trip connection: AtmosphericEntryHeatFromAdiabaticCompression ↔ ReificationRisk (score 4/5, analogy)
// Adiabatic compression theory risks reifying "reentry heating" as a unified phenomenon when shock-layer compression and surface friction may be answering different mechanistic questions about energy transfer.
// ---------------------------------------------------------------------------

var TripCycle3AtmosphericEntryHeatFromAdiabaticCompressionTheoryOfReificationRisk = TheoryOf{
	Subject: AtmosphericEntryHeatFromAdiabaticCompression,
	Object:  ReificationRisk,
	Prov: Conjecture{
		GeneratedBy:      "metabolism-trip",
		From:             []*Entity{AtmosphericEntryHeatFromAdiabaticCompression.Entity, ReificationRisk.Entity},
		CycleN:           3,
		Temperature:      0.8,
		PromptType:       "analogy",
		Score:            4,
		Rationale:        "Adiabatic compression theory risks reifying \"reentry heating\" as a unified phenomenon when shock-layer compression and surface friction may be answering different mechanistic questions about energy transfer. The adiabatic compression hypothesis exemplifies reification risk by potentially conflating a specific physical mechanism (shock-layer compression) with the broader observed phenomenon (reentry heating), much like multiple theories pointing at one concept-label can obscure whether they address the same underlying question or different aspects of it.",
		GeneratedAt:      "2026-04-17",
		GeneratedByAgent: "winze-metabolism-trip",
	},
}
