package winze

// Metabolism cycle 30: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: HierarchicalPredictionMachine ↔ KahnemanDualProcessFraming (score 4/5, analogy)
// Both HierarchicalPredictionMachine and KahnemanDualProcessFraming posit a layered cognitive architecture where faster/higher-level processes generate candidate outputs (predictions or System 1 judgments) that are monitored, overridden, or validated by slower/lower-level deliberation (prediction error correction or System 2 scrutiny).
// ---------------------------------------------------------------------------

var TripCycle30HierarchicalPredictionMachineStructurallyAnalogousToKahnemanDualProcessFraming = StructurallyAnalogousTo{
	Subject: HierarchicalPredictionMachine.Entity,
	Object:  KahnemanDualProcessFraming.Entity,
	Prov: Conjecture{
		GeneratedBy:      "metabolism-trip",
		From:             []*Entity{HierarchicalPredictionMachine.Entity, KahnemanDualProcessFraming.Entity},
		CycleN:           30,
		Temperature:      1.0,
		PromptType:       "analogy",
		Score:            4,
		Rationale:        "Both HierarchicalPredictionMachine and KahnemanDualProcessFraming posit a layered cognitive architecture where faster/higher-level processes generate candidate outputs (predictions or System 1 judgments) that are monitored, overridden, or validated by slower/lower-level deliberation (prediction error correction or System 2 scrutiny). Both frameworks share an isomorphic control structure: rapid generative process + error-detection loop by a deliberate system; the failure modes differ (prediction error vs. uncorrected bias) but the epistemic machinery—feed-forward + top-down monitoring—maps cleanly, and this analogy clarifies why biases persist when System 2 is cognitively taxed (resource-limited prediction error correction).",
		GeneratedAt:      "2026-09-06",
		GeneratedByAgent: "winze-metabolism-trip",
	},
}
