package winze

// Metabolism cycle 31: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: ShermerPatternicityFraming ↔ KahnemanDualProcessFraming (score 4/5, analogy)
// Both reframe cognitive errors not as failures of individual reasoning faculties, but as systematic outputs of how multiple processing systems or mechanisms interact under normal conditions.
// ---------------------------------------------------------------------------

var TripCycle31ShermerPatternicityFramingStructurallyAnalogousToKahnemanDualProcessFraming = StructurallyAnalogousTo{
	Subject: ShermerPatternicityFraming.Entity,
	Object:  KahnemanDualProcessFraming.Entity,
	Prov: Conjecture{
		GeneratedBy:      "metabolism-trip",
		From:             []*Entity{ShermerPatternicityFraming.Entity, KahnemanDualProcessFraming.Entity},
		CycleN:           31,
		Temperature:      1.0,
		PromptType:       "analogy",
		Score:            4,
		Rationale:        "Both reframe cognitive errors not as failures of individual reasoning faculties, but as systematic outputs of how multiple processing systems or mechanisms interact under normal conditions. Shermer normalizes pattern-detection error as an inevitable byproduct of how pattern-detection evolved; Kahneman-Tversky normalize biases as systematic failures of System 1 to be corrected by System 2. Both shift explanatory weight from individual irrationality to structural interaction—a shared epistemological move that dignifies error as revealing something true about cognition's architecture rather than personal deficit.",
		GeneratedAt:      "2026-09-08",
		GeneratedByAgent: "winze-metabolism-trip",
	},
}
