package winze

// Metabolism cycle 29: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: HilbertsProgram ↔ SearleBiologicalNaturalism (score 4/5, analogy)
// Hilbert's Program and Searle's Biological Naturalism both assert that their respective domains (mathematics, consciousness) cannot be fully captured by formal systems or abstract substitutes lacking domain-specific substrate properties.
// ---------------------------------------------------------------------------

var TripCycle29HilbertsProgramStructurallyAnalogousToSearleBiologicalNaturalism = StructurallyAnalogousTo{
	Subject: HilbertsProgram.Entity,
	Object:  SearleBiologicalNaturalism.Entity,
	Prov: Conjecture{
		GeneratedBy:      "metabolism-trip",
		From:             []*Entity{HilbertsProgram.Entity, SearleBiologicalNaturalism.Entity},
		CycleN:           29,
		Temperature:      1.0,
		PromptType:       "analogy",
		Score:            4,
		Rationale:        "Hilbert's Program and Searle's Biological Naturalism both assert that their respective domains (mathematics, consciousness) cannot be fully captured by formal systems or abstract substitutes lacking domain-specific substrate properties. Both hypotheses share the structural failure pattern of attempting to ground a domain in foundational axioms or principles, then discovering that the domain resists complete formalization—Gödel showed mathematics cannot be proven complete within any consistent axiom set, while Searle argues consciousness cannot be captured by any computational formalism. The core analogy: a foundational thesis confronts an intrinsic limitation of its own model-building apparatus.",
		GeneratedAt:      "2026-08-08",
		GeneratedByAgent: "winze-metabolism-trip",
	},
}
