package winze

// Metabolism cycle 28: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: HierarchicalPredictionMachine ↔ GodelFirstIncompletenessTheorem (score 4/5, analogy)
// Both hierarchical prediction and formal arithmetic systems encounter irreducible gaps between their generative apparatus and the truths they purport to capture—the brain's sensory predictions can never fully constrain all valid environmental states, just as arithmetic axioms cannot prove all true statements in their domain.
// ---------------------------------------------------------------------------

var TripCycle28HierarchicalPredictionMachineStructurallyAnalogousToGodelFirstIncompletenessTheorem = StructurallyAnalogousTo{
	Subject: HierarchicalPredictionMachine.Entity,
	Object:  GodelFirstIncompletenessTheorem.Entity,
	Prov: Conjecture{
		GeneratedBy:      "metabolism-trip",
		From:             []*Entity{HierarchicalPredictionMachine.Entity, GodelFirstIncompletenessTheorem.Entity},
		CycleN:           28,
		Temperature:      1.0,
		PromptType:       "analogy",
		Score:            4,
		Rationale:        "Both hierarchical prediction and formal arithmetic systems encounter irreducible gaps between their generative apparatus and the truths they purport to capture—the brain's sensory predictions can never fully constrain all valid environmental states, just as arithmetic axioms cannot prove all true statements in their domain. Both exhibit an isomorphic epistemic structure: a formal or mechanistic system of generative rules that is inherently incomplete relative to the space of truths it aims to model, revealing a fundamental asymmetry between what can be generated/proved and what exists/is true.",
		GeneratedAt:      "2026-08-07",
		GeneratedByAgent: "winze-metabolism-trip",
	},
}
