package winze

// Metabolism cycle 29: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: FormanPCEThesis ↔ MattsonSchizophreniaSPPDysregulationFraming (score 4/5, analogy)
// Both hypotheses identify a pathological or transcendent state as arising from dissolution of a normally operative boundary—either between content and contentlessness (Forman) or between real and fabricated patterns (Mattson)—that destabilizes the mind's capacity to model which aspects of experience are generated versus perceived.
// ---------------------------------------------------------------------------

var TripCycle29FormanPCEThesisStructurallyAnalogousToMattsonSchizophreniaSPPDysregulationFraming = StructurallyAnalogousTo{
	Subject: FormanPCEThesis.Entity,
	Object:  MattsonSchizophreniaSPPDysregulationFraming.Entity,
	Prov: Conjecture{
		GeneratedBy:      "metabolism-trip",
		From:             []*Entity{FormanPCEThesis.Entity, MattsonSchizophreniaSPPDysregulationFraming.Entity},
		CycleN:           29,
		Temperature:      1.0,
		PromptType:       "analogy",
		Score:            4,
		Rationale:        "Both hypotheses identify a pathological or transcendent state as arising from dissolution of a normally operative boundary—either between content and contentlessness (Forman) or between real and fabricated patterns (Mattson)—that destabilizes the mind's capacity to model which aspects of experience are generated versus perceived. The core isomorphism is a collapse of a filtering or discriminatory mechanism: Forman's PCE strips away the intentional structure that usually tags experience as \"about something,\" while Mattson's SPP dysregulation strips away the metacognitive tag that distinguishes self-generated from externally-given patterns. Both reframe the resulting state not as noise, but as a genuine epistemic condition with its own internal logic—suggesting they model the same type of failure in the mind's reality-modeling apparatus.",
		GeneratedAt:      "2026-08-31",
		GeneratedByAgent: "winze-metabolism-trip",
	},
}
