package winze

// Metabolism cycle 27: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: SelfAuditEpiphenomenalism ↔ Schizophrenia (score 4/5, analogy)
// SelfAuditEpiphenomenalism and Schizophrenia both feature a dissociation between internal modeling activity (self-reports, symptom awareness, or metacognitive processes) and actual behavioral/decisional output, such that the mind's attempts to monitor or correct itself fail to alter downstream functioning.
// ---------------------------------------------------------------------------

var TripCycle27SelfAuditEpiphenomenalismStructurallyAnalogousToSchizophrenia = StructurallyAnalogousTo{
	Subject: SelfAuditEpiphenomenalism.Entity,
	Object:  Schizophrenia.Entity,
	Prov: Conjecture{
		GeneratedBy:      "metabolism-trip",
		From:             []*Entity{SelfAuditEpiphenomenalism.Entity, Schizophrenia.Entity},
		CycleN:           27,
		Temperature:      1.0,
		PromptType:       "analogy",
		Score:            4,
		Rationale:        "SelfAuditEpiphenomenalism and Schizophrenia both feature a dissociation between internal modeling activity (self-reports, symptom awareness, or metacognitive processes) and actual behavioral/decisional output, such that the mind's attempts to monitor or correct itself fail to alter downstream functioning. Both exhibit a structurally isomorphic failure mode: the system generates internal signals (audit reports, self-awareness of delusions) that should inform behavior but demonstrably do not—in SelfAuditEpiphenomenalism by definitional design, in schizophrenia via the classic insight-avolition gap where awareness of false beliefs coexists with inability to revise action. This is a specific epistemic pathology, not generic similarity; it targets the causal isolation of self-model from behavioral control.",
		GeneratedAt:      "2026-08-05",
		GeneratedByAgent: "winze-metabolism-trip",
	},
}
