package winze

// Metabolism cycle 32: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: KahnemanDualProcessFraming ↔ HierarchicalPredictionMachine (score 4/5, analogy)
// Both frameworks decompose cognitive failure into a two-level architecture where a lower-level process generates an output that a higher-level process should correct but systematically fails to do so.
// ---------------------------------------------------------------------------

var TripCycle32KahnemanDualProcessFramingStructurallyAnalogousToHierarchicalPredictionMachine = StructurallyAnalogousTo{
	Subject: KahnemanDualProcessFraming.Entity,
	Object:  HierarchicalPredictionMachine.Entity,
	Prov: Conjecture{
		GeneratedBy:      "metabolism-trip",
		From:             []*Entity{KahnemanDualProcessFraming.Entity, HierarchicalPredictionMachine.Entity},
		CycleN:           32,
		Temperature:      1.0,
		PromptType:       "analogy",
		Score:            4,
		Rationale:        "Both frameworks decompose cognitive failure into a two-level architecture where a lower-level process generates an output that a higher-level process should correct but systematically fails to do so. Kahneman's System 1→System 2 correction loop is structurally isomorphic to hierarchical prediction's top-down expectation meeting bottom-up input: in both, a fast/automatic layer produces a candidate model (judgment or prediction), and a slower/supervisory layer has the mechanistic capacity to revise it but either fails, neglects, or resource-constrains that revision, yielding systematic error.",
		GeneratedAt:      "2026-09-09",
		GeneratedByAgent: "winze-metabolism-trip",
	},
}
