package winze

// Metabolism cycle 17: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: MindsBrainsAndPrograms1980 ↔ Nondualism (score 4/5, analogy)
// Both Searle's Chinese Room and Nondualism challenge the adequacy of subject-object dualism as a framework for understanding mind: Searle argues syntax (subject) cannot produce semantics (object), while Nondualism dissolves the very boundary between subject and object as illusory.
// ---------------------------------------------------------------------------

var tripCycle17MindsBrainsAndPrograms1980NondualismSource = Provenance{
	Origin:     "winze trip cycle 17 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-27",
	IngestedBy: "winze metabolism trip (score 4/5, analogy, temp=1.0)",
	Quote:      "Both Searle's Chinese Room and Nondualism challenge the adequacy of subject-object dualism as a framework for understanding mind: Searle argues syntax (subject) cannot produce semantics (object), while Nondualism dissolves the very boundary between subject and object as illusory. Searle's argument reveals a fundamental inadequacy in the dualistic model of mind (syntax vs. semantics, form vs. meaning), which parallels Nondualism's critique of subject-object duality itself—making the Chinese Room implicitly a commentary on the limitations of the very dualisms that structure Western epistemology.",
}

var TripCycle17MindsBrainsAndPrograms1980CommentaryOnNondualism = CommentaryOn{
	Subject: MindsBrainsAndPrograms1980,
	Object:  Nondualism,
	Prov:    tripCycle17MindsBrainsAndPrograms1980NondualismSource,
}
