package winze

// Metabolism cycle 15: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: Prediction ↔ DemonHauntedWorld (score 4/5, analogy)
// Prediction is the practical epistemological tool that "Demon-Haunted World" advocates for distinguishing scientific claims from pseudoscience, since testable predictions constitute the demarcation criterion Sagan championed.
// ---------------------------------------------------------------------------

var tripCycle15PredictionDemonHauntedWorldSource = Provenance{
	Origin:     "winze trip cycle 15 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-27",
	IngestedBy: "winze metabolism trip (score 4/5, analogy, temp=1.0)",
	Quote:      "Prediction is the practical epistemological tool that \"Demon-Haunted World\" advocates for distinguishing scientific claims from pseudoscience, since testable predictions constitute the demarcation criterion Sagan championed. Prediction as a concept sits at the heart of Sagan's demarcation project—falsifiable predictions are what separate science from pseudoscience—making it not just relevant but conceptually central to the book's epistemological argument.",
}

var TripCycle15PredictionCommentaryOnDemonHauntedWorld = CommentaryOn{
	Subject: Prediction,
	Object:  DemonHauntedWorld,
	Prov:    tripCycle15PredictionDemonHauntedWorldSource,
}
