package winze

// Metabolism cycle 25: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: GreatWallNotUniquelyVisibleFromSpace ↔ Advaita (score 4/5, analogy)
// Both Advaita and the Great Wall myth exemplify how intuitive, elegant claims about reality (non-duality or unique visibility) can obscure the actual structure of perception and evidence, revealing how minds construct false universals from limited epistemic perspectives.
// ---------------------------------------------------------------------------

var tripCycle25GreatWallNotUniquelyVisibleFromSpaceAdvaitaSource = Provenance{
	Origin:     "winze trip cycle 25 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-27",
	IngestedBy: "winze metabolism trip (score 4/5, analogy, temp=1.0)",
	Quote:      "Both Advaita and the Great Wall myth exemplify how intuitive, elegant claims about reality (non-duality or unique visibility) can obscure the actual structure of perception and evidence, revealing how minds construct false universals from limited epistemic perspectives. The connection is defensible because both entities expose a common epistemological failure: the mind's tendency to validate neat, appealing narratives (monistic reality or a singular iconic truth) without rigorous phenomenological verification, making the Great Wall myth a practical case study in the theory of how minds fail to validate claims—a core concern of epistemology of minds.",
}

var TripCycle25GreatWallNotUniquelyVisibleFromSpaceTheoryOfAdvaita = TheoryOf{
	Subject: GreatWallNotUniquelyVisibleFromSpace,
	Object:  Advaita,
	Prov:    tripCycle25GreatWallNotUniquelyVisibleFromSpaceAdvaitaSource,
}

// ---------------------------------------------------------------------------
// Trip connection: SurvivorshipBias ↔ SuperiorPatternProcessing (score 4/5, analogy)
// Survivorship bias represents a failure mode of superior pattern processing—where the mind's pattern-integration machinery selectively encodes only successful instances, creating a systematically distorted model of causality.
// ---------------------------------------------------------------------------

var tripCycle25SurvivorshipBiasSuperiorPatternProcessingSource = Provenance{
	Origin:     "winze trip cycle 25 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-27",
	IngestedBy: "winze metabolism trip (score 4/5, analogy, temp=1.0)",
	Quote:      "Survivorship bias represents a failure mode of superior pattern processing—where the mind's pattern-integration machinery selectively encodes only successful instances, creating a systematically distorted model of causality. Both concepts concern how minds encode and integrate information to build causal models; survivorship bias shows a specific pathology where pattern processing preferentially encodes visible successes while failing to equally weight invisible failures, leading to systematic epistemic error despite the deployment of otherwise sophisticated cognitive machinery.",
}

var TripCycle25SurvivorshipBiasCommentaryOnSuperiorPatternProcessing = CommentaryOn{
	Subject: SurvivorshipBias,
	Object:  SuperiorPatternProcessing,
	Prov:    tripCycle25SurvivorshipBiasSuperiorPatternProcessingSource,
}
