package winze

// Metabolism cycle 19: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: FreeEnergyPrinciple ↔ BaseRateNeglect (score 4/5, analogy)
// Base Rate Neglect represents a failure mode of the Free Energy Principle: agents minimize surprise using specific case information rather than updating their priors according to true statistical base rates, creating a systematic modeling error.
// ---------------------------------------------------------------------------

var tripCycle19FreeEnergyPrincipleBaseRateNeglectSource = Provenance{
	Origin:     "winze trip cycle 19 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-27",
	IngestedBy: "winze metabolism trip (score 4/5, analogy, temp=1.0)",
	Quote:      "Base Rate Neglect represents a failure mode of the Free Energy Principle: agents minimize surprise using specific case information rather than updating their priors according to true statistical base rates, creating a systematic modeling error. Both concepts address how agents construct and update internal models under uncertainty; Base Rate Neglect shows a concrete mechanism by which the FEP's optimization can diverge from accuracy when agents weight case-specific information too heavily relative to prior statistical structure—a defensible failure-mode relationship.",
}

var TripCycle19FreeEnergyPrincipleCommentaryOnBaseRateNeglect = CommentaryOn{
	Subject: FreeEnergyPrinciple,
	Object:  BaseRateNeglect,
	Prov:    tripCycle19FreeEnergyPrincipleBaseRateNeglectSource,
}
