package winze

// Metabolism cycle 6: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: AvailabilityHeuristic ↔ NondualAwareness (score 4/5, analogy)
// AvailabilityHeuristic is a failure mode of nondual awareness—where the unified field fractures into attended/unattended domains, with the attended domain mistaken for reality's full structure.
// ---------------------------------------------------------------------------

var tripCycle6AvailabilityHeuristicNondualAwarenessSource = Provenance{
	Origin:     "winze trip cycle 6 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-19",
	IngestedBy: "winze metabolism trip (score 4/5, analogy, temp=1.0)",
	Quote:      "AvailabilityHeuristic is a failure mode of nondual awareness—where the unified field fractures into attended/unattended domains, with the attended domain mistaken for reality's full structure. Both describe how consciousness models reality, but from inverse perspectives: nondual awareness posits a pre-conceptual unity, while availability heuristic reveals how that unity fragments into salient/non-salient partitions—making the heuristic a concrete epistemic failure of the unified field's capacity to represent the whole.",
}

var TripCycle6AvailabilityHeuristicCommentaryOnNondualAwareness = CommentaryOn{
	Subject: AvailabilityHeuristic,
	Object:  NondualAwareness,
	Prov:    tripCycle6AvailabilityHeuristicNondualAwarenessSource,
}

// ---------------------------------------------------------------------------
// Trip connection: Exomemory ↔ BaloneyDetectionKit (score 4/5, analogy)
// Exomemory functions as a societal-scale instantiation of the epistemic vulnerabilities that the BaloneyDetectionKit was designed to defend against—both concern systems for validating shared beliefs that can be corrupted by undetected manipulation.
// ---------------------------------------------------------------------------

var tripCycle6ExomemoryBaloneyDetectionKitSource = Provenance{
	Origin:     "winze trip cycle 6 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-19",
	IngestedBy: "winze metabolism trip (score 4/5, analogy, temp=1.0)",
	Quote:      "Exomemory functions as a societal-scale instantiation of the epistemic vulnerabilities that the BaloneyDetectionKit was designed to defend against—both concern systems for validating shared beliefs that can be corrupted by undetected manipulation. Exomemory embodies the epistemic nightmare Sagan warned about: a system for collective knowledge that is structurally vulnerable to exactly the kind of hidden manipulation and logical fallacy propagation that the BaloneyDetectionKit exists to detect, making it a practical instantiation of why those critical-thinking tools are essential.",
}

var TripCycle6ExomemoryCommentaryOnBaloneyDetectionKit = CommentaryOn{
	Subject: Exomemory,
	Object:  BaloneyDetectionKit,
	Prov:    tripCycle6ExomemoryBaloneyDetectionKitSource,
}
