package winze

// Metabolism cycle 21: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: KahnemanDualProcessFraming ↔ Mattson2014SPPPaper (score 4/5, analogy)
// Both frameworks propose that cognitive performance emerges from a hierarchical interaction between two distinct processing mechanisms—System 1/2's fast-intuitive vs. slow-analytical split mirrors the dual engagement of pattern-recognition versus error-correction in neural evolution.
// ---------------------------------------------------------------------------

var tripCycle21KahnemanDualProcessFramingMattson2014SPPPaperSource = Provenance{
	Origin:     "winze trip cycle 21 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-27",
	IngestedBy: "winze metabolism trip (score 4/5, analogy, temp=1.0)",
	Quote:      "Both frameworks propose that cognitive performance emerges from a hierarchical interaction between two distinct processing mechanisms—System 1/2's fast-intuitive vs. slow-analytical split mirrors the dual engagement of pattern-recognition versus error-correction in neural evolution. Kahneman's dual-process framing can be reinterpreted as a theory of how superior pattern processing (Mattson's mechanism) creates systematic failures when pattern-speed outpaces correction-speed, providing mechanistic explanation for why evolutionary adaptation produces cognitive biases rather than eliminating them.",
}

var TripCycle21KahnemanDualProcessFramingTheoryOfMattson2014SPPPaper = TheoryOf{
	Subject: KahnemanDualProcessFraming,
	Object:  Mattson2014SPPPaper,
	Prov:    tripCycle21KahnemanDualProcessFramingMattson2014SPPPaperSource,
}
