package winze

// Metabolism cycle 3 ingest: LLM-assisted claim extraction from
// corroborated ZIM articles identified by topology-driven sensor queries.
//
// Generated by: go run ./cmd/metabolism --ingest --zim <file> .
// Each claim was extracted by an LLM from the Wikipedia article text,
// constrained by mirror-source-commitments: only claims the source
// explicitly commits to are encoded. The provenance Quote field contains
// the exact source fragment supporting each claim.
//
// Review before committing: verify quotes are accurate and claims
// reflect what the source actually states.

// ---------------------------------------------------------------------------
// Hard problem of consciousness: Anil Seth Disputes ChalmersHardProblemThesis
// Seth explicitly rejects the existence of the hard problem thesis.
// ---------------------------------------------------------------------------

var anilSethDisputesSource = Provenance{
	Origin:     "Wikipedia (zim 2025-12) / Hard_problem_of_consciousness",
	IngestedAt: "2026-04-12",
	IngestedBy: "winze metabolism cycle 3 (LLM-assisted ingest from ZIM)",
	Quote:      "\"On the other hand, its existence is rejected by other philosophers of mind, such as Daniel Dennett, Massimo Pigliucci, Thomas Metzinger, Patricia Churchland, and Keith Frankish, and by cognitive neuroscientists such as Stanislas Dehaene, Bernard Baars, Anil Seth, and Antonio Damasio.\"",
}

// TODO: check if AnilSeth already exists in the KB (grep for "anil-seth")
var AnilSeth = Person{&Entity{
	ID:    "anil-seth",
	Name:  "Anil Seth",
	Kind:  "person",
	Brief: "Cognitive neuroscientist who rejects the existence of the hard problem of consciousness. Professor of Cognitive and Computational Neuroscience at the University of Sussex.",
}}

var AnilSethDisputesChalmersHardProblemThesis = Disputes{
	Subject: AnilSeth,
	Object:  ChalmersHardProblemThesis,
	Prov:    anilSethDisputesSource,
}

// ---------------------------------------------------------------------------
// Philosophical zombie: Christopher Hill Disputes ChalmersHardProblemThesis
// Hill disputes the hard problem thesis by arguing that zombies, while conceptually coherent, are metaphysically impossible, thereby rejecting the zombie argument's use in supporting the hard problem of consciousness.
// ---------------------------------------------------------------------------

var christopherHillDisputesSource = Provenance{
	Origin:     "Wikipedia (zim 2025-12) / Philosophical_zombie",
	IngestedAt: "2026-04-12",
	IngestedBy: "winze metabolism cycle 3 (LLM-assisted ingest from ZIM)",
	Quote:      "\"others, such as Christopher Hill, argue that philosophical zombies are coherent but metaphysically impossible.\"",
}

// TODO: check if ChristopherHill already exists in the KB (grep for "christopher-hill")
var ChristopherHill = Person{&Entity{
	ID:    "christopher-hill",
	Name:  "Christopher Hill",
	Kind:  "person",
	Brief: "Philosopher who argues that philosophical zombies are coherent but metaphysically impossible.",
}}

var ChristopherHillDisputesChalmersHardProblemThesis = Disputes{
	Subject: ChristopherHill,
	Object:  ChalmersHardProblemThesis,
	Prov:    christopherHillDisputesSource,
}
