package winze

// Metabolism cycle 3: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: AtmosphericEntryHeatFromAdiabaticCompression ↔ ReificationRisk (score 4/5, analogy)
// Adiabatic compression theory risks reifying "reentry heating" as a unified phenomenon when shock-layer compression and surface friction may be answering different mechanistic questions about energy transfer.
// ---------------------------------------------------------------------------

var tripCycle3AtmosphericEntryHeatFromAdiabaticCompressionReificationRiskSource = Provenance{
	Origin:     "winze trip cycle 3 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-17",
	IngestedBy: "winze metabolism trip (score 4/5, analogy, temp=0.8)",
	Quote:      "Adiabatic compression theory risks reifying \"reentry heating\" as a unified phenomenon when shock-layer compression and surface friction may be answering different mechanistic questions about energy transfer. The adiabatic compression hypothesis exemplifies reification risk by potentially conflating a specific physical mechanism (shock-layer compression) with the broader observed phenomenon (reentry heating), much like multiple theories pointing at one concept-label can obscure whether they address the same underlying question or different aspects of it.",
}

var TripCycle3AtmosphericEntryHeatFromAdiabaticCompressionTheoryOfReificationRisk = TheoryOf{
	Subject: AtmosphericEntryHeatFromAdiabaticCompression,
	Object:  ReificationRisk,
	Prov:    tripCycle3AtmosphericEntryHeatFromAdiabaticCompressionReificationRiskSource,
}
