package winze

// Metabolism cycle 11: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: GreatWallNotUniquelyVisibleFromSpace ↔ HumanCognition (score 4/5, analogy)
// Both HumanCognition and GreatWallNotUniquelyVisibleFromSpace exemplify how commonsense intuitions about their magnitude or special status collapse under empirical scrutiny—humans believe their minds are uniquely powerful, yet cognitive science reveals deep limitations and failures in perception, memory, and reasoning that parallel the public's false belief in the Wall's cosmic visibility.
// ---------------------------------------------------------------------------

var tripCycle11GreatWallNotUniquelyVisibleFromSpaceHumanCognitionSource = Provenance{
	Origin:     "winze trip cycle 11 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-27",
	IngestedBy: "winze metabolism trip (score 4/5, analogy, temp=1.0)",
	Quote:      "Both HumanCognition and GreatWallNotUniquelyVisibleFromSpace exemplify how commonsense intuitions about their magnitude or special status collapse under empirical scrutiny—humans believe their minds are uniquely powerful, yet cognitive science reveals deep limitations and failures in perception, memory, and reasoning that parallel the public's false belief in the Wall's cosmic visibility. The debunked hypothesis becomes a theory of HumanCognition's systematic failure: it reveals how minds construct inflated narratives about their own or humanity's achievements, mistaking cultural impressiveness for objective perceptual fact—a metacognitive blind spot worth modeling.",
}

var TripCycle11GreatWallNotUniquelyVisibleFromSpaceTheoryOfHumanCognition = TheoryOf{
	Subject: GreatWallNotUniquelyVisibleFromSpace,
	Object:  HumanCognition,
	Prov:    tripCycle11GreatWallNotUniquelyVisibleFromSpaceHumanCognitionSource,
}
