package winze

// Metabolism cycle 26: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: KahnemanDualProcessFraming ↔ ConradApopheniaClinicalFraming (score 4/5, analogy)
// Both KahnemanDualProcessFraming and ConradApopheniaClinicalFraming describe failures of metacognitive validation where automatic/prereflective processes generate outputs that conscious scrutiny should correct but does not.
// ---------------------------------------------------------------------------

var TripCycle26KahnemanDualProcessFramingStructurallyAnalogousToConradApopheniaClinicalFraming = StructurallyAnalogousTo{
	Subject: KahnemanDualProcessFraming,
	Object:  ConradApopheniaClinicalFraming,
	Prov: Conjecture{
		GeneratedBy:      "metabolism-trip",
		From:             []*Entity{KahnemanDualProcessFraming.Entity, ConradApopheniaClinicalFraming.Entity},
		CycleN:           26,
		Temperature:      1.0,
		PromptType:       "analogy",
		Score:            4,
		Rationale:        "Both KahnemanDualProcessFraming and ConradApopheniaClinicalFraming describe failures of metacognitive validation where automatic/prereflective processes generate outputs that conscious scrutiny should correct but does not. The shared pattern is a two-level epistemic architecture in which a first-order process (System 1 intuition or apophenic over-interpretation) produces candidate models that a higher-order process (System 2 deliberation or reality-checking) must filter; both hypotheses model cases where this validation fails structurally, not by random noise but by systematic properties of how meaning or judgment is constructed at the lower level.",
		GeneratedAt:      "2026-07-23",
		GeneratedByAgent: "winze-metabolism-trip",
	},
}
