package winze

// Metabolism cycle 2: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: StevenPinker ↔ LoyFiveFlavorsTypology (score 4/5, analogy)
// Both Pinker's evolutionary psychology and the Loy typology systematically deconstruct dualistic frameworks—one by reducing mind-behavior binaries to unified biological substrates, the other by collapsing subject-object and phenomenon-absolute distinctions into non-dual ontologies.
// ---------------------------------------------------------------------------

var tripCycle2StevenPinkerLoyFiveFlavorsTypologySource = Provenance{
	Origin:     "winze trip cycle 2 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-17",
	IngestedBy: "winze metabolism trip (score 4/5, analogy, temp=0.8)",
	Quote:      "Both Pinker's evolutionary psychology and the Loy typology systematically deconstruct dualistic frameworks—one by reducing mind-behavior binaries to unified biological substrates, the other by collapsing subject-object and phenomenon-absolute distinctions into non-dual ontologies. Both frameworks share a deep structural commitment to dissolving foundational dualisms (nature-nurture, mind-body, subject-object) through unifying principles, making them conceptual analogues despite operating in cognitive science versus metaphysics domains.",
}

var TripCycle2StevenPinkerProposesLoyFiveFlavorsTypology = Proposes{
	Subject: StevenPinker,
	Object:  LoyFiveFlavorsTypology,
	Prov:    tripCycle2StevenPinkerLoyFiveFlavorsTypologySource,
}

// ---------------------------------------------------------------------------
// Trip connection: SukhiShergill ↔ KeithCampbell (score 4/5, analogy)
// Shergill's empirical work on motor prediction and sensory attenuation provides a neurobiological resolution to the explanatory gap that Campbell's zombie argument exposed in 1970.
// ---------------------------------------------------------------------------

var tripCycle2SukhiShergillKeithCampbellSource = Provenance{
	Origin:     "winze trip cycle 2 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-17",
	IngestedBy: "winze metabolism trip (score 4/5, analogy, temp=0.8)",
	Quote:      "Shergill's empirical work on motor prediction and sensory attenuation provides a neurobiological resolution to the explanatory gap that Campbell's zombie argument exposed in 1970. Both thinkers address the hard problem of consciousness through complementary approaches—Campbell posed the logical problem of conceivability (zombies), while Shergill's predictive coding framework suggests how first-person sensory experience arises from motor-prediction mismatches, making the zombie scenario empirically implausible rather than merely conceptually incoherent.",
}

var TripCycle2SukhiShergillInfluencedByKeithCampbell = InfluencedBy{
	Subject: SukhiShergill,
	Object:  KeithCampbell,
	Prov:    tripCycle2SukhiShergillKeithCampbellSource,
}

// ---------------------------------------------------------------------------
// Trip connection: Mieli ↔ Apophenia (score 4/5, analogy)
// Mieli's role as an intermediary agent navigating between conflicting systems (Sobornost vs. Pellegrini) mirrors apophenia's function as a model-building failure—both involve imposed or constructed patterns that may not reflect underlying reality.
// ---------------------------------------------------------------------------

var tripCycle2MieliApopheniaSource = Provenance{
	Origin:     "winze trip cycle 2 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-17",
	IngestedBy: "winze metabolism trip (score 4/5, analogy, temp=0.8)",
	Quote:      "Mieli's role as an intermediary agent navigating between conflicting systems (Sobornost vs. Pellegrini) mirrors apophenia's function as a model-building failure—both involve imposed or constructed patterns that may not reflect underlying reality. Mieli operates within a vast surveillance/pattern-matching civilization (Sobornost) that enforces collective pattern interpretation; apophenia describes how minds impose false patterns when modeling reality—both represent the epistemological problem of distinguishing imposed structure from actual structure.",
}

var TripCycle2MieliCommentaryOnApophenia = CommentaryOn{
	Subject: Mieli,
	Object:  Apophenia,
	Prov:    tripCycle2MieliApopheniaSource,
}
