package winze

// Metabolism cycle 2: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// (Removed: StevenPinkerProposesLoyFiveFlavorsTypology — trip-fabricated
// Proposes claim. Pinker did not propose Loy's five-flavors typology; the
// trip cycle had no source-grounding step. Proposes is in
// tripBannedPredicates.)
//
// (Removed: SukhiShergillInfluencedByKeithCampbell — trip-fabricated
// InfluencedBy claim. No source-grounding for the biographical
// influence claim. InfluencedBy is in tripBannedPredicates.)

// ---------------------------------------------------------------------------
// Trip connection: Mieli ↔ Apophenia (score 4/5, analogy)
// Mieli's role as an intermediary agent navigating between conflicting systems (Sobornost vs. Pellegrini) mirrors apophenia's function as a model-building failure—both involve imposed or constructed patterns that may not reflect underlying reality.
// ---------------------------------------------------------------------------

var tripCycle2MieliApopheniaSource = Provenance{
	Origin:     "winze trip cycle 2 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-17",
	IngestedBy: "winze metabolism trip (score 4/5, analogy, temp=0.8)",
	Quote:      "Mieli's role as an intermediary agent navigating between conflicting systems (Sobornost vs. Pellegrini) mirrors apophenia's function as a model-building failure—both involve imposed or constructed patterns that may not reflect underlying reality. Mieli operates within a vast surveillance/pattern-matching civilization (Sobornost) that enforces collective pattern interpretation; apophenia describes how minds impose false patterns when modeling reality—both represent the epistemological problem of distinguishing imposed structure from actual structure.",
}

var TripCycle2MieliCommentaryOnApophenia = CommentaryOn{
	Subject: Mieli,
	Object:  Apophenia,
	Prov:    tripCycle2MieliApopheniaSource,
}
