package winze

// Metabolism cycle 22: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: WhiteShergillUsingIllusionsCommentary ↔ ArtificialStructureSpaceVisibility (score 4/5, analogy)
// Both expose how human perceptual/modeling systems fail to distinguish signal from noise under specific constraints—schizophrenia shows reduced susceptibility to optical illusions despite predictive coding predictions, while the Great Wall visibility myth shows how observers conflate resolution limits with presence, both representing failures of epistemic calibration.
// ---------------------------------------------------------------------------

var tripCycle22WhiteShergillUsingIllusionsCommentaryArtificialStructureSpaceVisibilitySource = Provenance{
	Origin:     "winze trip cycle 22 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-27",
	IngestedBy: "winze metabolism trip (score 4/5, analogy, temp=1.0)",
	Quote:      "Both expose how human perceptual/modeling systems fail to distinguish signal from noise under specific constraints—schizophrenia shows reduced susceptibility to optical illusions despite predictive coding predictions, while the Great Wall visibility myth shows how observers conflate resolution limits with presence, both representing failures of epistemic calibration. Both entities constitute corrective commentaries on folk theories of perception: Shergill challenges the assumption that weakened priors universally reduce illusion susceptibility, while the Great Wall visibility phenomenon challenges assumptions about what distance/resolution can reveal, making them parallel epistemic corrections despite different sensory domains.",
}

var TripCycle22WhiteShergillUsingIllusionsCommentaryCommentaryOnArtificialStructureSpaceVisibility = CommentaryOn{
	Subject: WhiteShergillUsingIllusionsCommentary,
	Object:  ArtificialStructureSpaceVisibility,
	Prov:    tripCycle22WhiteShergillUsingIllusionsCommentaryArtificialStructureSpaceVisibilitySource,
}
