package winze

// Metabolism cycle 25: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.
//
// 2026-04-27 audit: the first connection in this file
// (GreatWallNotUniquelyVisibleFromSpace TheoryOf Advaita) was deleted
// as a category-error TheoryOf misuse — a debunked-misconception entity
// is not a "theory of" Advaita metaphysics. The surviving connection
// (SurvivorshipBias CommentaryOn SuperiorPatternProcessing) was rated
// substantive: identifies a specific mechanistic failure mode
// (selective encoding of successes) within pattern-processing.

// ---------------------------------------------------------------------------
// Trip connection: SurvivorshipBias ↔ SuperiorPatternProcessing (score 4/5, analogy)
// Survivorship bias represents a failure mode of superior pattern processing—where the mind's pattern-integration machinery selectively encodes only successful instances, creating a systematically distorted model of causality.
// ---------------------------------------------------------------------------

var tripCycle25SurvivorshipBiasSuperiorPatternProcessingSource = Provenance{
	Origin:     "winze trip cycle 25 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-27",
	IngestedBy: "winze metabolism trip (score 4/5, analogy, temp=1.0)",
	Quote:      "Survivorship bias represents a failure mode of superior pattern processing—where the mind's pattern-integration machinery selectively encodes only successful instances, creating a systematically distorted model of causality. Both concepts concern how minds encode and integrate information to build causal models; survivorship bias shows a specific pathology where pattern processing preferentially encodes visible successes while failing to equally weight invisible failures, leading to systematic epistemic error despite the deployment of otherwise sophisticated cognitive machinery.",
}

var TripCycle25SurvivorshipBiasCommentaryOnSuperiorPatternProcessing = CommentaryOn{
	Subject: SurvivorshipBias,
	Object:  SuperiorPatternProcessing,
	Prov:    tripCycle25SurvivorshipBiasSuperiorPatternProcessingSource,
}
