package winze

// Metabolism cycle 4: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: HumanCognition ↔ EarthSeasons (score 4/5, contradiction)
// Human cognitive capacities for abstract reasoning and causal inference are systematically misled by seasonal phenomena, revealing a fundamental gap between intuitive physics and reality.
// ---------------------------------------------------------------------------

var tripCycle4HumanCognitionEarthSeasonsSource = Provenance{
	Origin:     "winze trip cycle 4 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-17",
	IngestedBy: "winze metabolism trip (score 4/5, contradiction, temp=1.0)",
	Quote:      "Human cognitive capacities for abstract reasoning and causal inference are systematically misled by seasonal phenomena, revealing a fundamental gap between intuitive physics and reality. The seasonal distance misconception (warmer when closer to sun) demonstrates that human reasoning, despite its sophistication, fails to build accurate models of physical causation—directly challenging claims about the reliability of human cognitive capacities as a tool for reality modeling.",
}

var TripCycle4HumanCognitionCommentaryOnEarthSeasons = CommentaryOn{
	Subject: HumanCognition,
	Object:  EarthSeasons,
	Prov:    tripCycle4HumanCognitionEarthSeasonsSource,
}

// (Removed: TripPromotionPassesContradictionCheckTheoryOfUDHR1948 — trip
// picked a reified meta-hypothesis from predictions.go as the Subject of
// a TheoryOf claim. Recursive amplification: the substrate's own
// self-reporting becomes claim material. Trip pair selection now
// excludes entities declared in predictions.go; see
// isReifiedEntityFile.)
