package winze

// Metabolism cycle 8: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: DunningKrugerEffect ↔ QuantitativeForecasting (score 4/5, analogy)
// The Dunning-Kruger effect reveals a systematic failure mode in how agents evaluate their own model-building capacity, which quantitative forecasting methods are designed to compensate for by replacing subjective confidence with formal statistical calibration.
// ---------------------------------------------------------------------------

var tripCycle8DunningKrugerEffectQuantitativeForecastingSource = Provenance{
	Origin:     "winze trip cycle 8 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-26",
	IngestedBy: "winze metabolism trip (score 4/5, analogy, temp=1.0)",
	Quote:      "The Dunning-Kruger effect reveals a systematic failure mode in how agents evaluate their own model-building capacity, which quantitative forecasting methods are designed to compensate for by replacing subjective confidence with formal statistical calibration. Both entities address core epistemological problems: DK-effect documents metacognitive blindness about modeling ability, while quantitative forecasting is a structural solution to precisely this problem—replacing fallible self-assessment with systematic, externally-validated methods that bypass subjective bias.",
}

var TripCycle8DunningKrugerEffectCommentaryOnQuantitativeForecasting = CommentaryOn{
	Subject: DunningKrugerEffect,
	Object:  QuantitativeForecasting,
	Prov:    tripCycle8DunningKrugerEffectQuantitativeForecastingSource,
}
