package winze

// Metabolism cycle 5: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: TheCausalAngel ↔ AvailabilityHeuristic (score 4/5, genealogy)
// TheCausalAngel dramatizes how minds privileging recent, emotionally intense memories of loss and war (Jean and Mieli's separation, Perhonen's destruction) systematically mismodel strategic reality, instantiating the availability heuristic as narrative and consequence.
// ---------------------------------------------------------------------------

var tripCycle5TheCausalAngelAvailabilityHeuristicSource = Provenance{
	Origin:     "winze trip cycle 5 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-17",
	IngestedBy: "winze metabolism trip (score 4/5, genealogy, temp=0.9)",
	Quote:      "TheCausalAngel dramatizes how minds privileging recent, emotionally intense memories of loss and war (Jean and Mieli's separation, Perhonen's destruction) systematically mismodel strategic reality, instantiating the availability heuristic as narrative and consequence. The novel's central tragedy—agents making devastating decisions based on vivid, emotionally charged memories rather than ground truth—directly enacts the epistemological failure that availability heuristic describes, making it a sophisticated literary exploration of this cognitive bias.",
}

var TripCycle5TheCausalAngelCommentaryOnAvailabilityHeuristic = CommentaryOn{
	Subject: TheCausalAngel,
	Object:  AvailabilityHeuristic,
	Prov:    tripCycle5TheCausalAngelAvailabilityHeuristicSource,
}

// ---------------------------------------------------------------------------
// Trip connection: AnnDruyan ↔ DavidHilbert (score 3/5, genealogy)
// Ann Druyan's framework for evaluating scientific claims and epistemological rigor in The Demon-Haunted World was influenced by the foundational crisis in mathematics sparked by Hilbert's program and Gödel's response.
// ---------------------------------------------------------------------------

var tripCycle5AnnDruyanDavidHilbertSource = Provenance{
	Origin:     "winze trip cycle 5 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-17",
	IngestedBy: "winze metabolism trip (score 3/5, genealogy, temp=0.9)",
	Quote:      "Ann Druyan's framework for evaluating scientific claims and epistemological rigor in The Demon-Haunted World was influenced by the foundational crisis in mathematics sparked by Hilbert's program and Gödel's response. Druyan's emphasis on skepticism, the limits of formal systems, and how minds can be deceived aligns with the deeper lesson of Gödel's incompleteness theorems—that formal systems cannot prove their own consistency—a foundational epistemic insight that would naturally inform science communication about the mind's fallibility.",
}

var TripCycle5AnnDruyanInfluencedByDavidHilbert = InfluencedBy{
	Subject: AnnDruyan,
	Object:  DavidHilbert,
	Prov:    tripCycle5AnnDruyanDavidHilbertSource,
}
