package winze

// Metabolism cycle 13: trip-promoted speculative connections.
//
// These claims were generated by the REM-like trip cycle, which picks
// entity pairs from different topology clusters and asks an LLM to
// generate speculative relationships. Only connections scoring 4+/5
// are promoted. Provenance is marked as speculative.

// ---------------------------------------------------------------------------
// Trip connection: VolkerThreeTypesTypology ↔ Schizophrenia (score 4/5, analogy)
// Both schizophrenia and the Volker typology represent fundamentally different modal structures for reality-modeling, where the cognitive/perceptual apparatus generates competing frameworks (symptomatic vs. transcendent) that fail to integrate observer-observed boundaries
// ---------------------------------------------------------------------------

var tripCycle13VolkerThreeTypesTypologySchizophreniaSource = Provenance{
	Origin:     "winze trip cycle 13 (speculative cross-cluster connection)",
	IngestedAt: "2026-04-27",
	IngestedBy: "winze metabolism trip (score 4/5, analogy, temp=1.0)",
	Quote:      "Both schizophrenia and the Volker typology represent fundamentally different modal structures for reality-modeling, where the cognitive/perceptual apparatus generates competing frameworks (symptomatic vs. transcendent) that fail to integrate observer-observed boundaries The Volker typology—especially its asymmetric-vertical and symmetric-horizontal variants—can be understood as a theory explaining how minds construct different ontological models by dissolving or restructuring the observer-observed divide, a process that parallels schizophrenia's pathological breakdown of reality-modeling through hallucination and delusion; both involve radical reconfigurations of the epistemic subject's access to consensus reality.",
}

var TripCycle13VolkerThreeTypesTypologyTheoryOfSchizophrenia = TheoryOf{
	Subject: VolkerThreeTypesTypology,
	Object:  Schizophrenia,
	Prov:    tripCycle13VolkerThreeTypesTypologySchizophreniaSource,
}
