package winze

// Metabolism cycle 4 ingest: LLM-assisted claim extraction from
// corroborated ZIM articles identified by topology-driven sensor queries.
//
// Generated by: go run ./cmd/metabolism --ingest --zim <file> .
// Each claim was extracted by an LLM from the Wikipedia article text,
// constrained by mirror-source-commitments: only claims the source
// explicitly commits to are encoded. The provenance Quote field contains
// the exact source fragment supporting each claim.
//
// Review before committing: verify quotes are accurate and claims
// reflect what the source actually states.

// ---------------------------------------------------------------------------
// Hard problem of consciousness: Bernard Baars Disputes ChalmersHardProblemThesis
// The article explicitly states that Baars rejects the existence of the hard problem,
// ---------------------------------------------------------------------------

var bernardBaarsDisputesSource = Provenance{
	Origin:     "Wikipedia (zim 2025-12) / Hard_problem_of_consciousness",
	IngestedAt: "2026-04-12",
	IngestedBy: "winze metabolism cycle 4 (LLM-assisted ingest from ZIM)",
	Quote:      "\"On the other hand, its existence is rejected by other philosophers of mind, such as Daniel Dennett, Massimo Pigliucci, Thomas Metzinger, Patricia Churchland, and Keith Frankish, and by cognitive neuroscientists such as Stanislas Dehaene, Bernard Baars, Anil Seth, and Antonio Damasio.\"",
}

// TODO: check if BernardBaars already exists in the KB (grep for "bernard-baars")
var BernardBaars = Person{&Entity{
	ID:    "bernard-baars",
	Name:  "Bernard Baars",
	Kind:  "person",
	Brief: "Cognitive neuroscientist who rejects the existence of the hard problem of consciousness.",
}}

var BernardBaarsDisputesChalmersHardProblemThesis = Disputes{
	Subject: BernardBaars,
	Object:  ChalmersHardProblemThesis,
	Prov:    bernardBaarsDisputesSource,
}

// ---------------------------------------------------------------------------
// Philosophical zombie: Galen Strawson Disputes ChalmersHardProblemThesis
// Strawson explicitly disputes the foundational premise of Chalmers's hard problem thesis by arguing that zombies cannot be established as conceivable, thereby undermining the zombie argument that supports the hard problem.
// ---------------------------------------------------------------------------

var galenStrawsonDisputesSource = Provenance{
	Origin:     "Wikipedia (zim 2025-12) / Philosophical_zombie",
	IngestedAt: "2026-04-12",
	IngestedBy: "winze metabolism cycle 4 (LLM-assisted ingest from ZIM)",
	Quote:      "\"Galen Strawson argues that it is not possible to establish the conceivability of zombies, so the argument, lacking its first premise, can never get going.\"",
}

// TODO: check if GalenStrawson already exists in the KB (grep for "galen-strawson")
var GalenStrawson = Person{&Entity{
	ID:    "galen-strawson",
	Name:  "Galen Strawson",
	Kind:  "person",
	Brief: "A philosopher who argues against the conceivability of philosophical zombies.",
}}

var GalenStrawsonDisputesChalmersHardProblemThesis = Disputes{
	Subject: GalenStrawson,
	Object:  ChalmersHardProblemThesis,
	Prov:    galenStrawsonDisputesSource,
}
