package main

import (
	"bufio"
	"context"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/anthropics/anthropic-sdk-go"
	"github.com/anthropics/anthropic-sdk-go/option"
	zim "github.com/justinstimatze/gozim"
)

// runIngest performs LLM-assisted ingest from corroborated ZIM metabolism cycles.
//
// Pipeline:
//  1. Load metabolism log, filter for corroborated ZIM cycles with papers
//  2. For each corroborated article, read the ZIM article text
//  3. Collect hypothesis info from the KB (name, brief, existing proposers/disputants)
//  4. Call Anthropic API: extract claims the source explicitly commits to
//  5. Generate .go corpus file from LLM response
//  6. Validate with go build
func runIngest(dir, zimPath, zimIndex string) {
	loadDotEnv(dir)

	apiKey := os.Getenv("ANTHROPIC_API_KEY")
	if apiKey == "" {
		fmt.Fprintf(os.Stderr, "metabolism: --ingest requires ANTHROPIC_API_KEY (set in .env or environment)\n")
		os.Exit(1)
	}

	// Open ZIM archive
	archive, err := zim.Open(zimPath, zim.WithMmap())
	if err != nil {
		fmt.Fprintf(os.Stderr, "metabolism: open zim: %v\n", err)
		os.Exit(1)
	}
	defer archive.Close()

	// Load metabolism log
	logPath := filepath.Join(dir, ".metabolism-log.json")
	mlog := loadLog(logPath)

	// Collect corroborated ZIM cycles with papers, grouped by hypothesis
	type ingestTarget struct {
		hypothesis string
		prediction string
		articles   []PaperSummary // ZIM articles (ID is "zim:<path>")
	}
	seen := map[string]*ingestTarget{}
	var order []string
	for _, c := range mlog.Cycles {
		if c.Resolution != "corroborated" || c.PapersFound == 0 || c.Backend != "zim" {
			continue
		}
		if t, ok := seen[c.Hypothesis]; ok {
			t.articles = append(t.articles, c.Papers...)
		} else {
			seen[c.Hypothesis] = &ingestTarget{
				hypothesis: c.Hypothesis,
				prediction: c.Prediction,
				articles:   append([]PaperSummary{}, c.Papers...),
			}
			order = append(order, c.Hypothesis)
		}
	}

	if len(order) == 0 {
		fmt.Fprintln(os.Stderr, "metabolism: no corroborated ZIM cycles with papers — nothing to ingest")
		return
	}

	// Deduplicate articles per hypothesis
	for _, t := range seen {
		idSeen := map[string]bool{}
		var deduped []PaperSummary
		for _, p := range t.articles {
			if !idSeen[p.ID] {
				idSeen[p.ID] = true
				deduped = append(deduped, p)
			}
		}
		t.articles = deduped
	}

	// Collect entity briefs and claim context from the KB
	briefs := collectKBBriefs(dir)
	claimCtx := collectClaimContext(dir)

	cycleNum := nextCycleNumber(dir)
	outPath := filepath.Join(dir, fmt.Sprintf("metabolism_cycle%d.go", cycleNum))

	fmt.Printf("[ingest] %d corroborated hypotheses, writing to %s\n", len(order), filepath.Base(outPath))

	var sections []string
	sections = append(sections, fmt.Sprintf("package winze\n\n"+
		"// Metabolism cycle %d ingest: LLM-assisted claim extraction from\n"+
		"// corroborated ZIM articles identified by topology-driven sensor queries.\n"+
		"//\n"+
		"// Generated by: go run ./cmd/metabolism --ingest --zim <file> .\n"+
		"// Each claim was extracted by an LLM from the Wikipedia article text,\n"+
		"// constrained by mirror-source-commitments: only claims the source\n"+
		"// explicitly commits to are encoded. The provenance Quote field contains\n"+
		"// the exact source fragment supporting each claim.\n"+
		"//\n"+
		"// Review before committing: verify quotes are accurate and claims\n"+
		"// reflect what the source actually states.\n",
		cycleNum))

	client := anthropic.NewClient(option.WithAPIKey(apiKey))
	totalClaims := 0

	for _, hypName := range order {
		t := seen[hypName]

		hypBrief := briefs[hypName]
		existingClaims := claimCtx[hypName]

		// Determine what kind of claim we need
		needType := "Proposes" // single-source → need second proposer
		if strings.Contains(t.prediction, "uncontested") {
			needType = "Disputes" // uncontested → need disputant
		}

		fmt.Printf("\n  %s (%s needed)\n", hypName, needType)

		for _, article := range t.articles {
			// Strip "zim:" prefix to get the article path
			artPath := strings.TrimPrefix(article.ID, "zim:")

			// Read article content
			artText, err := readZimArticle(archive, artPath)
			if err != nil {
				fmt.Fprintf(os.Stderr, "    skip %s: %v\n", article.Title, err)
				continue
			}

			// Truncate to ~12000 chars (~3000 tokens) to keep enough
			// context for meaningful quote extraction
			if len(artText) > 12000 {
				artText = artText[:12000] + "\n[...truncated...]"
			}

			fmt.Printf("    reading %s (%d chars)...\n", article.Title, len(artText))

			// Build and send the LLM prompt
			prompt := buildIngestPrompt(hypName, hypBrief, needType, existingClaims, article, artText)
			resp, err := callIngestLLM(client, prompt)
			if err != nil {
				fmt.Fprintf(os.Stderr, "    LLM error: %v\n", err)
				continue
			}

			// Parse the LLM response
			result := parseIngestResponse(resp)
			if result == nil {
				fmt.Printf("    → no actionable claim (source doesn't commit)\n")
				continue
			}

			// Verify quote exists in source text (grep-only verification)
			if !verifyQuote(artText, result.quote) {
				fmt.Printf("    → QUOTE MISMATCH: %s (quote not found in source, skipping)\n", result.entityName)
				continue
			}

			fmt.Printf("    → %s %s %s\n", result.entityName, needType, hypName)

			// Generate Go code
			section := generateClaimCode(hypName, needType, article, result, cycleNum)
			sections = append(sections, section)
			totalClaims++
		}
	}

	if totalClaims == 0 {
		fmt.Println("\n[ingest] no actionable claims extracted — sources didn't commit to relationships")
		return
	}

	// Write the file
	content := strings.Join(sections, "\n")
	if err := os.WriteFile(outPath, []byte(content), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "metabolism: write %s: %v\n", outPath, err)
		os.Exit(1)
	}

	// Validate with go build
	fmt.Printf("\n[ingest] wrote %d claims to %s, validating...\n", totalClaims, filepath.Base(outPath))
	cmd := exec.Command("go", "build", "./...")
	cmd.Dir = dir
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "\n[ingest] WARNING: go build failed — generated code needs manual fixes\n")
		fmt.Fprintf(os.Stderr, "  edit %s to fix compilation errors, then run:\n", outPath)
		fmt.Fprintf(os.Stderr, "  go build ./... && go run ./cmd/lint .\n")
	} else {
		fmt.Printf("[ingest] go build passed — %d claims ready for review\n", totalClaims)
	}
}

// readZimArticle reads a ZIM article by path and returns stripped plaintext.
func readZimArticle(archive *zim.Archive, path string) (string, error) {
	entry, err := archive.GetEntryByPath(path)
	if err != nil {
		return "", fmt.Errorf("get entry %q: %w", path, err)
	}

	// Follow redirects (up to 5 hops)
	for i := 0; i < 5 && entry.IsRedirect(); i++ {
		entry, err = entry.RedirectTarget()
		if err != nil {
			return "", fmt.Errorf("resolve redirect %q: %w", path, err)
		}
	}

	content, err := entry.Content()
	if err != nil {
		return "", fmt.Errorf("read content %q: %w", path, err)
	}

	return stripHTML(content), nil
}

// buildIngestPrompt constructs the LLM prompt for claim extraction.
func buildIngestPrompt(hypName, hypBrief, needType string, existingClaims []string, article PaperSummary, articleText string) string {
	var b strings.Builder

	b.WriteString("You are extracting knowledge claims from a Wikipedia article for a typed knowledge base.\n\n")

	b.WriteString("## Rules\n\n")
	b.WriteString("1. MIRROR-SOURCE-COMMITMENTS: Only extract claims the source EXPLICITLY states. ")
	b.WriteString("Do not infer, extrapolate, or fabricate relationships.\n")
	b.WriteString("2. If the source does not explicitly commit to a ")
	b.WriteString(needType)
	b.WriteString(" relationship with the hypothesis below, respond with EXACTLY: NO_CLAIM\n")
	b.WriteString("3. Extract the EXACT quote from the article that supports the claim. ")
	b.WriteString("The quote must be 1-3 complete sentences copied verbatim from the article. ")
	b.WriteString("Do NOT truncate or paraphrase.\n")
	b.WriteString("4. Identify the specific person or organization making the claim.\n\n")

	b.WriteString("## Target hypothesis\n\n")
	b.WriteString(fmt.Sprintf("Variable name: %s\n", hypName))
	if hypBrief != "" {
		b.WriteString(fmt.Sprintf("Description: %s\n", hypBrief))
	}
	b.WriteString(fmt.Sprintf("\nWe need a %s claim — ", needType))
	if needType == "Proposes" {
		b.WriteString("a person or organization that independently supports or endorses this hypothesis.\n")
	} else {
		b.WriteString("a person or organization that explicitly disputes, criticizes, or argues against this hypothesis.\n")
	}

	if len(existingClaims) > 0 {
		b.WriteString(fmt.Sprintf("\nExisting claims (do NOT duplicate these):\n"))
		for _, c := range existingClaims {
			b.WriteString(fmt.Sprintf("  - %s\n", c))
		}
	}

	b.WriteString(fmt.Sprintf("\n## Source article: %s\n\n", article.Title))
	b.WriteString(articleText)
	b.WriteString("\n\n")

	b.WriteString("## Response format\n\n")
	b.WriteString("If the article explicitly commits to a " + needType + " relationship, respond with EXACTLY this format:\n\n")
	b.WriteString("ENTITY_NAME: <full name of the person or organization>\n")
	b.WriteString("ENTITY_ID: <kebab-case-id>\n")
	b.WriteString("ENTITY_KIND: <person or organization>\n")
	b.WriteString("ENTITY_BRIEF: <one sentence description>\n")
	b.WriteString("QUOTE: <exact text from the article supporting this claim>\n")
	b.WriteString("EXPLANATION: <one sentence on why this constitutes a " + needType + " relationship>\n\n")
	b.WriteString("If the article does NOT explicitly commit to such a relationship, respond with EXACTLY:\nNO_CLAIM\n")

	return b.String()
}

type ingestResult struct {
	entityName  string
	entityID    string
	entityKind  string
	entityBrief string
	quote       string
	explanation string
}

// parseIngestResponse parses the LLM's structured response.
func parseIngestResponse(response string) *ingestResult {
	response = strings.TrimSpace(response)
	if strings.HasPrefix(response, "NO_CLAIM") {
		return nil
	}

	result := &ingestResult{}
	for _, line := range strings.Split(response, "\n") {
		line = strings.TrimSpace(line)
		if v, ok := strings.CutPrefix(line, "ENTITY_NAME:"); ok {
			result.entityName = strings.TrimSpace(v)
		} else if v, ok := strings.CutPrefix(line, "ENTITY_ID:"); ok {
			result.entityID = strings.TrimSpace(v)
		} else if v, ok := strings.CutPrefix(line, "ENTITY_KIND:"); ok {
			result.entityKind = strings.TrimSpace(v)
		} else if v, ok := strings.CutPrefix(line, "ENTITY_BRIEF:"); ok {
			result.entityBrief = strings.TrimSpace(v)
		} else if v, ok := strings.CutPrefix(line, "QUOTE:"); ok {
			result.quote = strings.TrimSpace(v)
		} else if v, ok := strings.CutPrefix(line, "EXPLANATION:"); ok {
			result.explanation = strings.TrimSpace(v)
		}
	}

	if result.entityName == "" || result.quote == "" {
		return nil
	}

	// Defaults
	if result.entityID == "" {
		result.entityID = strings.ToLower(strings.ReplaceAll(result.entityName, " ", "-"))
	}
	if result.entityKind == "" {
		result.entityKind = "person"
	}

	return result
}

// generateClaimCode produces Go source code for a single extracted claim.
func generateClaimCode(hypName, claimType string, article PaperSummary, result *ingestResult, cycleNum int) string {
	var b strings.Builder

	// Convert entity name to a Go variable name (PascalCase)
	varName := toPascalCase(result.entityName)
	provVar := lowerFirst(varName) + upperFirst(claimType) + "Source"
	claimVar := varName + upperFirst(claimType) + hypName

	// Clean LLM artifacts from strings
	quote := cleanLLMString(result.quote)
	brief := cleanLLMString(result.entityBrief)

	b.WriteString(fmt.Sprintf("// ---------------------------------------------------------------------------\n"))
	b.WriteString(fmt.Sprintf("// %s: %s %s %s\n", article.Title, result.entityName, claimType, hypName))
	if result.explanation != "" {
		b.WriteString(fmt.Sprintf("// %s\n", result.explanation))
	}
	b.WriteString(fmt.Sprintf("// ---------------------------------------------------------------------------\n\n"))

	// Provenance
	b.WriteString(fmt.Sprintf("var %s = Provenance{\n", provVar))
	b.WriteString(fmt.Sprintf("\tOrigin:     \"Wikipedia (zim 2025-12) / %s\",\n", strings.TrimPrefix(article.ID, "zim:")))
	b.WriteString(fmt.Sprintf("\tIngestedAt: %q,\n", time.Now().Format("2006-01-02")))
	b.WriteString(fmt.Sprintf("\tIngestedBy: \"winze metabolism cycle %d (LLM-assisted ingest from ZIM)\",\n", cycleNum))
	b.WriteString(fmt.Sprintf("\tQuote:      %q,\n", quote))
	b.WriteString("}\n\n")

	// Entity (check if it might already exist)
	roleType := "Person"
	if result.entityKind == "organization" {
		roleType = "Organization"
	}
	b.WriteString(fmt.Sprintf("// TODO: check if %s already exists in the KB (grep for %q)\n", varName, result.entityID))
	b.WriteString(fmt.Sprintf("var %s = %s{&Entity{\n", varName, roleType))
	b.WriteString(fmt.Sprintf("\tID:    %q,\n", result.entityID))
	b.WriteString(fmt.Sprintf("\tName:  %q,\n", result.entityName))
	b.WriteString(fmt.Sprintf("\tKind:  %q,\n", result.entityKind))
	b.WriteString(fmt.Sprintf("\tBrief: %q,\n", brief))
	b.WriteString("}}\n\n")

	// Claim
	subjType := roleType
	predType := claimType
	if result.entityKind == "organization" && claimType == "Proposes" {
		predType = "ProposesOrg"
	} else if result.entityKind == "organization" && claimType == "Disputes" {
		predType = "DisputesOrg"
	}
	_ = subjType
	b.WriteString(fmt.Sprintf("var %s = %s{\n", claimVar, predType))
	b.WriteString(fmt.Sprintf("\tSubject: %s,\n", varName))
	b.WriteString(fmt.Sprintf("\tObject:  %s,\n", hypName))
	b.WriteString(fmt.Sprintf("\tProv:    %s,\n", provVar))
	b.WriteString("}\n")

	return b.String()
}

// callIngestLLM calls the Anthropic API for claim extraction.
func callIngestLLM(client anthropic.Client, prompt string) (string, error) {
	resp, err := client.Messages.New(context.Background(), anthropic.MessageNewParams{
		Model:     anthropic.ModelClaudeHaiku4_5,
		MaxTokens: 1024,
		Messages: []anthropic.MessageParam{
			anthropic.NewUserMessage(anthropic.NewTextBlock(prompt)),
		},
	})
	if err != nil {
		return "", fmt.Errorf("API error: %w", err)
	}

	for _, block := range resp.Content {
		if block.Type == "text" {
			return block.Text, nil
		}
	}
	return "", fmt.Errorf("no text content in response")
}

// --- helpers ---

// collectKBBriefs walks .go files and extracts Brief fields from entity
// composite literals, similar to cmd/lint/llm.go's collectBriefs.
func collectKBBriefs(dir string) map[string]string {
	briefs := map[string]string{}
	fset := token.NewFileSet()

	entries, err := os.ReadDir(dir)
	if err != nil {
		return briefs
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(dir, e.Name()), nil, parser.SkipObjectResolution)
		if err != nil {
			continue
		}
		for _, decl := range f.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.VAR {
				continue
			}
			for _, spec := range gen.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}
				for i, nameIdent := range vs.Names {
					if i >= len(vs.Values) {
						continue
					}
					cl, ok := vs.Values[i].(*ast.CompositeLit)
					if !ok {
						continue
					}
					brief := extractEntityBrief(cl)
					if brief != "" {
						briefs[nameIdent.Name] = brief
					}
				}
			}
		}
	}
	return briefs
}

// extractEntityBrief extracts the Brief field from a role-typed entity literal.
func extractEntityBrief(cl *ast.CompositeLit) string {
	for _, elt := range cl.Elts {
		// Direct KV (in Entity{} literals)
		if kv, ok := elt.(*ast.KeyValueExpr); ok {
			if key, ok := kv.Key.(*ast.Ident); ok && key.Name == "Brief" {
				return unquote(kv.Value)
			}
			continue
		}
		// RoleType{&Entity{...}} pattern
		ue, ok := elt.(*ast.UnaryExpr)
		if !ok {
			continue
		}
		inner, ok := ue.X.(*ast.CompositeLit)
		if !ok {
			continue
		}
		for _, innerElt := range inner.Elts {
			if kv, ok := innerElt.(*ast.KeyValueExpr); ok {
				if key, ok := kv.Key.(*ast.Ident); ok && key.Name == "Brief" {
					return unquote(kv.Value)
				}
			}
		}
	}
	return ""
}

// collectClaimContext returns existing Proposes/Disputes claims per hypothesis.
func collectClaimContext(dir string) map[string][]string {
	claims := map[string][]string{} // hypothesis var name → claim descriptions
	fset := token.NewFileSet()

	entries, err := os.ReadDir(dir)
	if err != nil {
		return claims
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(dir, e.Name()), nil, parser.SkipObjectResolution)
		if err != nil {
			continue
		}
		for _, decl := range f.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.VAR {
				continue
			}
			for _, spec := range gen.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}
				for i, nameIdent := range vs.Names {
					if i >= len(vs.Values) {
						continue
					}
					cl, ok := vs.Values[i].(*ast.CompositeLit)
					if !ok {
						continue
					}
					predType := compositeTypeName(cl)
					if predType != "Proposes" && predType != "Disputes" &&
						predType != "ProposesOrg" && predType != "DisputesOrg" {
						continue
					}
					subj, obj := extractSubjectObject(cl)
					if obj != "" {
						claims[obj] = append(claims[obj],
							fmt.Sprintf("%s: %s %s %s", nameIdent.Name, subj, predType, obj))
					}
				}
			}
		}
	}
	return claims
}

func compositeTypeName(cl *ast.CompositeLit) string {
	switch t := cl.Type.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.IndexExpr:
		if id, ok := t.X.(*ast.Ident); ok {
			return id.Name
		}
	}
	return ""
}

func extractSubjectObject(cl *ast.CompositeLit) (string, string) {
	var subj, obj string
	for _, elt := range cl.Elts {
		kv, ok := elt.(*ast.KeyValueExpr)
		if !ok {
			continue
		}
		key, ok := kv.Key.(*ast.Ident)
		if !ok {
			continue
		}
		switch key.Name {
		case "Subject":
			if id, ok := kv.Value.(*ast.Ident); ok {
				subj = id.Name
			}
		case "Object":
			if id, ok := kv.Value.(*ast.Ident); ok {
				obj = id.Name
			}
		}
	}
	return subj, obj
}

func unquote(e ast.Expr) string {
	lit, ok := e.(*ast.BasicLit)
	if !ok || lit.Kind != token.STRING {
		return ""
	}
	s, err := strconv.Unquote(lit.Value)
	if err != nil {
		return lit.Value
	}
	return s
}

func toPascalCase(name string) string {
	words := strings.Fields(name)
	var parts []string
	for _, w := range words {
		if len(w) > 0 {
			parts = append(parts, strings.ToUpper(w[:1])+strings.ToLower(w[1:]))
		}
	}
	return strings.Join(parts, "")
}

func lowerFirst(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func upperFirst(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// verifyQuote checks that the LLM's extracted quote actually appears in the
// source text. Uses normalized substring matching — collapses whitespace and
// checks that at least a 40-char fragment of the quote appears verbatim.
// This catches LLM hallucination/paraphrasing without being brittle to
// minor whitespace differences from HTML stripping.
func verifyQuote(sourceText, quote string) bool {
	// Normalize: collapse whitespace, lowercase
	normalize := func(s string) string {
		return strings.ToLower(strings.Join(strings.Fields(s), " "))
	}

	normSource := normalize(sourceText)
	normQuote := normalize(quote)

	// Remove surrounding quotes the LLM may have added
	normQuote = strings.Trim(normQuote, `"'`)

	if len(normQuote) < 20 {
		return false // quote too short to be meaningful
	}

	// Check if the full normalized quote is a substring
	if strings.Contains(normSource, normQuote) {
		return true
	}

	// Check sliding window of 40-char fragments (handles truncation)
	fragLen := 40
	if len(normQuote) < fragLen {
		fragLen = len(normQuote)
	}
	// Check the first fragment and a middle fragment
	if strings.Contains(normSource, normQuote[:fragLen]) {
		return true
	}
	mid := len(normQuote) / 2
	if mid+fragLen <= len(normQuote) {
		if strings.Contains(normSource, normQuote[mid:mid+fragLen]) {
			return true
		}
	}

	return false
}

func cleanLLMString(s string) string {
	// Clean up common LLM artifacts before Go's %q handles escaping
	s = strings.ReplaceAll(s, `\"`, `"`)
	s = strings.ReplaceAll(s, `\n`, " ")
	s = strings.ReplaceAll(s, "\u201c", `"`) // left smart quote
	s = strings.ReplaceAll(s, "\u201d", `"`) // right smart quote
	s = strings.ReplaceAll(s, "\u2018", "'") // left smart single quote
	s = strings.ReplaceAll(s, "\u2019", "'") // right smart single quote
	return strings.TrimSpace(s)
}

// loadDotEnv reads KEY=VALUE pairs from .env in the given directory.
func loadDotEnv(dir string) {
	path := filepath.Join(dir, ".env")
	f, err := os.Open(path)
	if err != nil {
		return
	}
	defer f.Close() //nolint:errcheck
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}
		key := strings.TrimSpace(parts[0])
		val := strings.TrimSpace(parts[1])
		if os.Getenv(key) == "" {
			os.Setenv(key, val)
		}
	}
}
