package main

import (
	"os"
	"path/filepath"
	"testing"
)

// TestExistingReifyCycleCount covers the parse half of the shrink guard.
// The guard itself calls os.Exit and cannot be exercised in-process, so the
// testable unit is the header read that decides whether it fires.
func TestExistingReifyCycleCount(t *testing.T) {
	dir := t.TempDir()

	cases := []struct {
		name string
		body string
		want int
	}{
		{
			name: "real header",
			body: "package winze\n\n// Prediction reification: ...\n//\n// Generated by: go run ./cmd/metabolism --reify .\n// Source: .metabolism-log.json (376 cycles, 52 hypotheses, 2026-04-12 to 2026-07-23)\n",
			want: 376,
		},
		{
			// The exact shape that regenerated over 376 cycles of history.
			name: "post-shrink header",
			body: "package winze\n// Source: .metabolism-log.json (44 cycles, 9 hypotheses, 2026-08-03 to 2026-08-05)\n",
			want: 44,
		},
		{
			name: "no header — fail open, guard must not fire on a hand-written file",
			body: "package winze\n\nvar X = 1\n",
			want: -1,
		},
		{
			name: "malformed count",
			body: "package winze\n// Source: .metabolism-log.json (many cycles, 9 hypotheses)\n",
			want: -1,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			p := filepath.Join(dir, tc.name+".go")
			if err := os.WriteFile(p, []byte(tc.body), 0o644); err != nil {
				t.Fatalf("write fixture: %v", err)
			}
			if got := existingReifyCycleCount(p); got != tc.want {
				t.Errorf("existingReifyCycleCount = %d, want %d", got, tc.want)
			}
		})
	}

	if got := existingReifyCycleCount(filepath.Join(dir, "absent.go")); got != -1 {
		t.Errorf("absent file = %d, want -1 (no previous state to compare)", got)
	}
}

// TestReifyHeaderIsParseableByItsOwnGuard closes the loop between the
// generator and the guard: runReify writes the header, existingReifyCycleCount
// reads it, and nothing enforces that they agree. If the header format is ever
// reworded, the guard silently returns -1 and stops guarding — failing open in
// the one direction that costs history.
func TestReifyHeaderIsParseableByItsOwnGuard(t *testing.T) {
	const corpus = "../../corpus/predictions.go"
	if _, err := os.Stat(corpus); err != nil {
		t.Skip("corpus/predictions.go not present")
	}
	if got := existingReifyCycleCount(corpus); got <= 0 {
		t.Errorf("guard cannot read the live generated header (got %d) — "+
			"the emit format in runReify and reifySourceRe have drifted apart", got)
	}
}
