package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// fixtureLog builds a metabolism log covering the shapes reify's date handling
// actually branches on: a hypothesis with resolutions (so the resolution-history
// comment is emitted with a date), one whose cycles are all unresolved (so the
// date must be omitted rather than defaulted to now), and a KB-internal
// prediction type alongside a sensor one, since those take different emit paths.
func fixtureLog() MetabolismLog {
	at := func(day int) time.Time {
		return time.Date(2026, 3, day, 12, 0, 0, 0, time.UTC)
	}
	return MetabolismLog{Cycles: []Cycle{
		{
			Timestamp: at(1), Hypothesis: "ThinNeighborhood", Prediction: "arXiv will corroborate",
			Query: "epistemic closure", Backend: "arxiv", VulnType: "orphan", VulnCount: 3,
			PapersFound: 2, Resolution: "corroborated", ResolvedAt: "2026-03-02",
		},
		{
			Timestamp: at(4), Hypothesis: "ThinNeighborhood", Prediction: "arXiv will corroborate",
			Query: "epistemic closure", Backend: "arxiv", VulnType: "orphan", VulnCount: 3,
			PapersFound: 1, Resolution: "challenged", ResolvedAt: "2026-03-05",
		},
		{
			// Never resolved: the history comment must carry no date at all
			// rather than borrowing the clock.
			Timestamp: at(6), Hypothesis: "UnresolvedBranch", Prediction: "nothing yet",
			Query: "dangling", Backend: "zim", VulnType: "orphan", VulnCount: 1,
		},
		{
			Timestamp: at(9), Hypothesis: "LintDurability", Prediction: "the promoted claim survives lint",
			Query: "n/a", VulnType: "durability", VulnCount: 1,
			Resolution: "corroborated", ResolvedAt: "2026-03-09",
			PredictionType: "trip_lint_durability", Evidence: "lint clean",
		},
	}}
}

// reifyOnce runs the reifier against a scratch dir holding only the given log
// and returns the generated file.
//
// The returned error is deliberately ignored: runReify's last act is a
// `go build ./...` gate, and a bare temp dir is not a Go module, so that gate
// always fails here. It fails *after* the file is written, which is what this
// test reads. Compiling the output is a different property, already covered by
// the corpus build gate on the real predictions.go — what is under test here is
// whether the generated bytes depend on anything but the log.
func reifyOnce(t *testing.T, dir string, mlog MetabolismLog) string {
	t.Helper()
	if err := saveLog(filepath.Join(dir, ".metabolism-log.json"), mlog); err != nil {
		t.Fatalf("saveLog: %v", err)
	}
	_ = runReify(dir)
	out, err := os.ReadFile(filepath.Join(dir, "predictions.go"))
	if err != nil {
		t.Fatalf("reify wrote no predictions.go: %v", err)
	}
	return string(out)
}

// TestReifyIsDeterministic is the ratchet on the churn this file was added for.
//
// predictions.go is a pure function of .metabolism-log.json — the whole file is
// rebuilt and overwritten on every cycle. When runReify stamped time.Now() into
// the provenance and the resolution-history comments, that stopped being true:
// the output became a function of when the generator ran, so an unchanged log
// still produced a diff, and cmd/metabolize's len(changed)==0 quiet-cycle guard
// never fired. 65 of the 67 metabolism commits between 2026-07-23 and
// 2026-08-22 were exactly that — twelve consecutive days whose entire delta was
// `IngestedAt` and `reified` dates advancing by one.
//
// A date fix alone is a one-time correction. This test is what stops the next
// time.Now() from reintroducing it, and it runs the generator three times
// because the second run is the first one to overwrite an existing file — the
// steady state production is always in.
func TestReifyIsDeterministic(t *testing.T) {
	dir := t.TempDir()
	first := reifyOnce(t, dir, fixtureLog())
	second := reifyOnce(t, dir, fixtureLog())
	third := reifyOnce(t, dir, fixtureLog())

	if second != third {
		t.Errorf("steady-state regeneration is not stable: run 2 and run 3 differ\n%s", firstDiff(second, third))
	}
	if first != second {
		t.Errorf("first regeneration differs from the second — something depends on whether predictions.go already existed\n%s", firstDiff(first, second))
	}
}

// TestReifyDatesComeFromTheLogNotTheClock pins the specific values, so a
// regression that happens to be *consistently* wrong — a clock read cached once
// per process, say — still fails. TestReifyIsDeterministic alone would pass on
// that.
func TestReifyDatesComeFromTheLogNotTheClock(t *testing.T) {
	out := reifyOnce(t, t.TempDir(), fixtureLog())

	// IngestedAt is the newest cycle in the log (2026-03-09), never today.
	if !strings.Contains(out, `IngestedAt: "2026-03-09"`) {
		t.Errorf("IngestedAt is not the newest cycle date 2026-03-09; got:\n%s", grepLine(out, "IngestedAt:"))
	}
	// The resolved hypothesis carries its own last resolution date.
	if !strings.Contains(out, "resolved through 2026-03-05") {
		t.Errorf("resolution history does not carry the hypothesis's own last ResolvedAt (2026-03-05); got:\n%s", grepLine(out, "Resolution history"))
	}
	if y := time.Now().Format("2006"); strings.Contains(out, "reified "+y) {
		t.Errorf("output still contains a %s `reified` stamp — the clock is back in the generator", y)
	}
}

// TestReifyOmitsTheDateWhenNothingResolved covers the case where reaching for
// the clock is most tempting and least correct: a hypothesis with no
// ResolvedAt at all. The honest output is no date, not today's.
func TestReifyOmitsTheDateWhenNothingResolved(t *testing.T) {
	for _, line := range strings.Split(reifyOnce(t, t.TempDir(), fixtureLog()), "\n") {
		line = strings.TrimSpace(line)
		if !strings.Contains(line, "Resolution history") {
			continue
		}
		if line == "// Resolution history:" || strings.Contains(line, "resolved through ") {
			continue
		}
		t.Errorf("history comment carries a date from neither the log nor nothing: %q", line)
	}
}

// firstDiff reports the first differing line, which is more useful than dumping
// two 5000-line files at a failure.
func firstDiff(a, b string) string {
	la, lb := strings.Split(a, "\n"), strings.Split(b, "\n")
	for i := 0; i < len(la) && i < len(lb); i++ {
		if la[i] != lb[i] {
			return "line " + itoa(i+1) + ":\n  A: " + la[i] + "\n  B: " + lb[i]
		}
	}
	return "identical line-for-line but different length: " + itoa(len(la)) + " vs " + itoa(len(lb))
}

func grepLine(s, needle string) string {
	for _, line := range strings.Split(s, "\n") {
		if strings.Contains(line, needle) {
			return strings.TrimSpace(line)
		}
	}
	return "(no line containing " + needle + ")"
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var b []byte
	for n > 0 {
		b = append([]byte{byte('0' + n%10)}, b...)
		n /= 10
	}
	return string(b)
}

// TestReifyOmitsBarrenSensorSearches is the test for the fix to the
// "metabolism reifies every search as an Event" problem: a hypothesis asked
// repeatedly that never got past irrelevant/no_signal is activity, not a
// finding, and must not appear in the corpus at all — no Event, no Predicts,
// no ResolvedAs. It is still fully present in .metabolism-log.json, which is
// not what this test reads; only predictions.go is.
//
// Contrasted against a KB-internal resolver deliberately: those write
// confirmed/refuted once per distinct trip candidate rather than repeating a
// question, so they are out of this filter's scope and must still be reified
// even when their outcome is refuted.
func TestReifyOmitsBarrenSensorSearches(t *testing.T) {
	at := func(day int) time.Time { return time.Date(2026, 3, day, 12, 0, 0, 0, time.UTC) }
	mlog := MetabolismLog{Cycles: []Cycle{
		{
			Timestamp: at(1), Hypothesis: "GenuineFinding", Prediction: "arXiv will corroborate",
			Query: "q", Backend: "arxiv", Resolution: "corroborated", ResolvedAt: "2026-03-01",
		},
		{
			Timestamp: at(2), Hypothesis: "BarrenRepeat", Prediction: "arXiv will corroborate",
			Query: "q2", Backend: "arxiv", Resolution: "irrelevant", ResolvedAt: "2026-03-02",
		},
		{
			Timestamp: at(3), Hypothesis: "BarrenRepeat", Prediction: "arXiv will corroborate",
			Query: "q2", Backend: "arxiv", Resolution: "no_signal", ResolvedAt: "2026-03-03",
		},
		{
			Timestamp: at(4), Hypothesis: "BuildFailureCase", Prediction: "n/a",
			Query: "n/a", VulnType: "buildability", VulnCount: 1,
			Resolution: "refuted", ResolvedAt: "2026-03-04",
			PredictionType: "trip_promotion_attempt", Evidence: "does not compile",
		},
	}}

	out := reifyOnce(t, t.TempDir(), mlog)

	if !strings.Contains(out, "EvidenceSearchGenuineFinding") {
		t.Error("a substantive sensor hypothesis must still be reified")
	}
	if strings.Contains(out, "BarrenRepeat") {
		t.Error("a repeatedly-irrelevant sensor hypothesis must not appear in the corpus at all")
	}
	if !strings.Contains(out, "BuildFailureCase") {
		t.Error("a KB-internal refuted check is out of this filter's scope and must still be reified")
	}
}
