// Trip cycle: REM-like speculative cross-cluster connection generation.
//
// Deliberately over-connects — picks entity pairs from different topology
// clusters and asks an LLM to generate speculative relationships. A second
// LLM pass judges interestingness. Interesting connections become candidate
// claims for human or pipeline review.
//
// Two orthogonal axes:
//   - Temperature: wildness of connection (0.0 conservative, 1.5 psychedelic)
//   - Prompt type: kind of connection (analogy, contradiction, genealogy, prediction)
//
// Together they form a "drug profile" for each trip cycle run.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"math/rand"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/anthropics/anthropic-sdk-go"
	"github.com/anthropics/anthropic-sdk-go/option"
	"github.com/justinstimatze/winze/internal/defndb"
)

// --- trip types ---

type tripEntity struct {
	name     string
	roleType string
	brief    string
	file     string
	cluster  int
}

type tripPair struct {
	A tripEntity
	B tripEntity
}

// tripGroup is a set of 3-5 entities for confluence/synthesis modes.
type tripGroup struct {
	Entities []tripEntity
}

// TripConnection is a speculative connection generated by the trip cycle.
type TripConnection struct {
	EntityA     string   `json:"entity_a"`
	EntityB     string   `json:"entity_b"`
	ClusterA    int      `json:"cluster_a"`
	ClusterB    int      `json:"cluster_b"`
	Entities    []string `json:"entities,omitempty"`    // confluence/synthesis: all entity names
	GroupSize   int      `json:"group_size,omitempty"`  // confluence/synthesis: number of entities
	PromptType  string   `json:"prompt_type"`
	Temperature float64  `json:"temperature"`
	Connection  string   `json:"connection"`
	Narrative   string   `json:"narrative,omitempty"`   // confluence/synthesis: full narrative
	NewConcept  string   `json:"new_concept,omitempty"` // synthesis: proposed new concept name
	Predicate   string   `json:"predicate,omitempty"`
	Subject     string   `json:"subject,omitempty"` // which entity is Subject (for predicate direction)
	Score       int      `json:"score"`             // 1-5 interestingness
	Rationale   string   `json:"rationale"`
}

type TripReport struct {
	Pairs       int              `json:"pairs_evaluated"`
	Connections []TripConnection `json:"connections"`
	DrugProfile string           `json:"drug_profile"`
	Temperature float64          `json:"temperature"`
	PromptType  string           `json:"prompt_type"`
}

// isGroupPrompt returns true for prompt types that operate on entity groups
// rather than pairs (confluence picks 3, synthesis picks 3-5).
func isGroupPrompt(promptType string) bool {
	return promptType == "confluence" || promptType == "synthesis"
}

func runTrip(dir string, temperature float64, promptType string, nPairs int, dryRun bool, jsonOut bool) TripReport {
	validPrompts := map[string]bool{
		"analogy": true, "contradiction": true, "genealogy": true, "prediction": true,
		"confluence": true, "synthesis": true,
	}
	if !validPrompts[promptType] {
		fmt.Fprintf(os.Stderr, "trip: --prompt-type must be analogy, contradiction, genealogy, prediction, confluence, or synthesis (got %q)\n", promptType)
		os.Exit(1)
	}
	if temperature < 0 || temperature > 1.0 {
		fmt.Fprintf(os.Stderr, "trip: --temperature must be 0.0-1.0 (got %.1f)\n", temperature)
		os.Exit(1)
	}

	// Characterize the drug profile
	profile := drugProfile(temperature, promptType)

	// 1. Collect entities with cluster membership
	entities := collectTripEntities(dir)
	if len(entities) == 0 {
		fmt.Println("[trip] no entities found")
		return TripReport{}
	}

	// Count clusters
	clusterSet := map[int]bool{}
	for _, e := range entities {
		clusterSet[e.cluster] = true
	}

	fmt.Printf("[trip] %d entities, %d clusters — profile: %s (temp=%.1f, prompt=%s)\n",
		len(entities), len(clusterSet), profile, temperature, promptType)

	// Branch: group-based (confluence/synthesis) vs pair-based
	if isGroupPrompt(promptType) {
		return runGroupTrip(dir, entities, temperature, promptType, nPairs, dryRun, jsonOut, profile)
	}

	// 2. Pick cross-cluster pairs
	pairs := pickCrossClusterPairs(entities, nPairs)
	if len(pairs) == 0 {
		fmt.Println("[trip] no cross-cluster pairs possible (all entities in one cluster?)")
		return TripReport{}
	}

	fmt.Printf("[trip] selected %d cross-cluster pairs\n", len(pairs))

	if dryRun {
		fmt.Println("\n  dry run — would evaluate:")
		for _, p := range pairs {
			fmt.Printf("    [%d] %-30s ↔ [%d] %-30s\n",
				p.A.cluster, p.A.name, p.B.cluster, p.B.name)
		}
		return TripReport{Pairs: len(pairs), DrugProfile: profile, Temperature: temperature, PromptType: promptType}
	}

	// 3. LLM: generate + judge connections
	loadDotEnv(dir)
	apiKey := os.Getenv("ANTHROPIC_API_KEY")
	if apiKey == "" {
		fmt.Fprintf(os.Stderr, "[trip] ANTHROPIC_API_KEY required\n")
		os.Exit(1)
	}
	client := anthropic.NewClient(option.WithAPIKey(apiKey))

	var connections []TripConnection
	for i, p := range pairs {
		fmt.Printf("  [%d/%d] %s ↔ %s ... ", i+1, len(pairs), p.A.name, p.B.name)

		conn, err := generateConnection(client, p, promptType, temperature)
		if err != nil {
			fmt.Printf("error: %v\n", err)
			continue
		}
		connections = append(connections, conn)

		marker := "·"
		if conn.Score >= 4 {
			marker = "!"
		} else if conn.Score >= 3 {
			marker = "*"
		}
		fmt.Printf("%s score=%d\n", marker, conn.Score)
	}

	report := TripReport{
		Pairs:       len(pairs),
		Connections: connections,
		DrugProfile: profile,
		Temperature: temperature,
		PromptType:  promptType,
	}

	printTripReport(report, jsonOut)
	return report
}

// runGroupTrip handles confluence and synthesis prompt types, which operate
// on groups of 3-5 entities rather than pairs. Implements the REBUS model:
// flattened priors (thin entities weighted equally), entropic coupling
// (synthesis includes isolates), narrative output with separate scoring.
func runGroupTrip(dir string, entities []tripEntity, temperature float64, promptType string, nGroups int, dryRun bool, jsonOut bool, profile string) TripReport {
	groupSize := 3
	if promptType == "synthesis" {
		groupSize = 3 + rand.Intn(3) // 3-5
	}

	groups := pickEntityGroups(entities, nGroups, groupSize, promptType == "synthesis")
	if len(groups) == 0 {
		fmt.Printf("[trip] no groups of %d possible\n", groupSize)
		return TripReport{}
	}

	fmt.Printf("[trip] selected %d groups of %d entities\n", len(groups), groupSize)

	if dryRun {
		fmt.Println("\n  dry run — would evaluate:")
		for i, g := range groups {
			names := make([]string, len(g.Entities))
			for j, e := range g.Entities {
				names[j] = fmt.Sprintf("[%d]%s", e.cluster, e.name)
			}
			fmt.Printf("    group %d: %s\n", i+1, strings.Join(names, " ~ "))
		}
		return TripReport{Pairs: len(groups), DrugProfile: profile, Temperature: temperature, PromptType: promptType}
	}

	loadDotEnv(dir)
	apiKey := os.Getenv("ANTHROPIC_API_KEY")
	if apiKey == "" {
		fmt.Fprintf(os.Stderr, "[trip] ANTHROPIC_API_KEY required\n")
		os.Exit(1)
	}
	client := anthropic.NewClient(option.WithAPIKey(apiKey))

	var connections []TripConnection
	for i, g := range groups {
		names := make([]string, len(g.Entities))
		for j, e := range g.Entities {
			names[j] = e.name
		}
		fmt.Printf("  [%d/%d] %s ... ", i+1, len(groups), strings.Join(names, " ~ "))

		conn, err := generateGroupConnection(client, g, promptType, temperature)
		if err != nil {
			fmt.Printf("error: %v\n", err)
			continue
		}
		connections = append(connections, conn)

		marker := "·"
		if conn.Score >= 4 {
			marker = "!"
		} else if conn.Score >= 3 {
			marker = "*"
		}
		fmt.Printf("%s score=%d\n", marker, conn.Score)
	}

	report := TripReport{
		Pairs:       len(groups),
		Connections: connections,
		DrugProfile: profile,
		Temperature: temperature,
		PromptType:  promptType,
	}

	printTripReport(report, jsonOut)
	return report
}

// printTripReport outputs the trip report as JSON or formatted text.
func printTripReport(report TripReport, jsonOut bool) {
	if jsonOut {
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		if err := enc.Encode(report); err != nil {
			fmt.Fprintf(os.Stderr, "trip: JSON encode: %v\n", err)
		}
		return
	}

	connections := report.Connections
	fmt.Printf("\n[trip] %d connections generated\n\n", len(connections))

	sort.Slice(connections, func(i, j int) bool {
		return connections[i].Score > connections[j].Score
	})

	for _, c := range connections {
		marker := " "
		switch {
		case c.Score >= 4:
			marker = "!"
		case c.Score >= 3:
			marker = "*"
		default:
			marker = "·"
		}

		if len(c.Entities) > 0 {
			// Group-based output
			fmt.Printf("  %s [%d/5] %s\n", marker, c.Score, strings.Join(c.Entities, " ~ "))
			if c.NewConcept != "" {
				fmt.Printf("          new concept: %s\n", c.NewConcept)
			}
			if c.Narrative != "" {
				// Indent narrative lines
				for _, line := range strings.Split(c.Narrative, "\n") {
					if line = strings.TrimSpace(line); line != "" {
						fmt.Printf("          %s\n", line)
					}
				}
			} else {
				fmt.Printf("          %s\n", c.Connection)
			}
		} else {
			// Pair-based output
			fmt.Printf("  %s [%d/5] %s ↔ %s\n", marker, c.Score, c.EntityA, c.EntityB)
			fmt.Printf("          %s\n", c.Connection)
		}
		if c.Predicate != "" {
			fmt.Printf("          predicate: %s\n", c.Predicate)
		}
		fmt.Printf("          rationale: %s\n\n", c.Rationale)
	}

	interesting := 0
	for _, c := range connections {
		if c.Score >= 3 {
			interesting++
		}
	}
	fmt.Printf("[trip] %d/%d connections scored >= 3 (interesting)\n", interesting, len(connections))
	fmt.Println("  legend: ! score 4-5 (promote)  * score 3 (review)  · score 1-2 (drop)")
}

// predicateSlots encodes the Subject/Object role-type constraints for each
// predicate that trip promotion knows how to emit. Keep in sync with predicates.go.
// A predicate not listed here cannot be promoted — add it deliberately.
//
// IMPORTANT: when adding a Person-attribution predicate (Proposes-family,
// Authored-family, Accepts-family, InfluencedBy, EarlyFormulationOf,
// ResolvedAs, or anything else asserting intellectual/biographical fact
// about a real person), also add it to tripBannedPredicates. The trip
// cycle has no source-grounding step, so Person-attribution claims it
// generates would be fabrications. See feedback memory
// feedback_trip_promotion_fabrication.md.
var predicateSlots = map[string]struct {
	Subject string
	Object  string
}{
	"InfluencedBy": {"Person", "Person"},
	"DerivedFrom":  {"Concept", "Concept"},
	"BelongsTo":    {"Concept", "Concept"},
	"Disputes":     {"Person", "Hypothesis"},
	"Proposes":     {"Person", "Hypothesis"},
	"Accepts":      {"Person", "Hypothesis"},
	"TheoryOf":     {"Hypothesis", "Concept"},
	"CommentaryOn": {"Concept", "Concept"},
}

// validatePredicate returns true iff predicate's type constraints match subjRole→objRole.
func validatePredicate(pred, subjRole, objRole string) bool {
	slots, ok := predicateSlots[pred]
	if !ok {
		return false
	}
	return slots.Subject == subjRole && slots.Object == objRole
}

// compatiblePredicates returns predicates where some ordering of (roleA, roleB)
// satisfies the predicate's slot constraints. Used to filter the LLM prompt.
func compatiblePredicates(roleA, roleB string) []string {
	var out []string
	for pred, slots := range predicateSlots {
		if (slots.Subject == roleA && slots.Object == roleB) ||
			(slots.Subject == roleB && slots.Object == roleA) {
			out = append(out, pred)
		}
	}
	sort.Strings(out)
	return out
}

// tripBannedPredicates lists predicates the trip cycle MUST NOT promote.
// The line drawn here: ban predicates whose Subject is a Person and whose
// semantics assert intellectual commitment or biographical fact about
// that Person. Fabricating any of these is a mirror-source-commitments
// violation: the corpus would assert "X said Y" or "A was influenced by
// B" without grounding evidence.
//
// Currently bans:
//   - Proposes, Disputes, Accepts: Person → Hypothesis. Assert that a
//     specific Person committed to a position on a hypothesis.
//   - InfluencedBy: Person → Person. Asserts a biographical claim about
//     intellectual influence between two real people.
//
// Knowingly permitted (with the gap noted in feedback memory):
//   - TheoryOf, CommentaryOn, BelongsTo, DerivedFrom: Concept/Hypothesis
//     subjects, no Person attribution. Trip-fabricated nonsense in these
//     shapes is a category error ("AdiabaticCompression TheoryOf
//     ReificationRisk") rather than a false attribution to a real
//     person. Less corrosive but not harmless. The cleaner long-term
//     fix is a separate SpeculativeProposes-style predicate type or
//     mandatory source grounding; until then these predicates are
//     allowed because banning them would empty the trip emit menu.
//
// Future predicateSlots additions that are Person-attribution must also
// be added here: ProposesOrg, DisputesOrg, AcceptsOrg, Authored,
// AuthoredOrg, EarlyFormulationOf, and ResolvedAs all qualify. See the
// comment on predicateSlots and the reviewer prompt in
// feedback_trip_promotion_fabrication.md.
//
// Reverted commit 4e350dc (session 8) is the case study: 8 fabricated
// "X Proposes Y" claims promoted in one cycle with the bias active.
var tripBannedPredicates = map[string]bool{
	"Proposes":     true,
	"Disputes":     true,
	"Accepts":      true,
	"InfluencedBy": true,
}

// tripCompatiblePredicates is compatiblePredicates with attribution
// predicates filtered out. Used everywhere the trip cycle hands a
// predicate menu to the LLM — keeps the generator from picking
// predicates we'll later refuse to promote.
func tripCompatiblePredicates(roleA, roleB string) []string {
	all := compatiblePredicates(roleA, roleB)
	out := make([]string, 0, len(all))
	for _, p := range all {
		if !tripBannedPredicates[p] {
			out = append(out, p)
		}
	}
	return out
}

// promoteConnections converts high-scoring trip connections into corpus claims.
// Only promotes connections with Score >= minScore, a valid predicate, both
// entities existing in the KB, and type-compatible Subject/Object slots.
// Writes to a new metabolism_cycleN.go file with quality gates.
func promoteConnections(dir string, connections []TripConnection, minScore int) error {
	// Filter for promotable connections
	var promotable []TripConnection
	for _, c := range connections {
		if c.Score >= minScore && c.Predicate != "" && c.Predicate != "NONE" {
			promotable = append(promotable, c)
		}
	}
	if len(promotable) == 0 {
		fmt.Printf("[trip-promote] no connections scored %d+ with valid predicate\n", minScore)
		return nil
	}

	// Collect entity vars + role types for validation
	entityVars := collectEntityVarNames(dir)
	entityRoles := collectEntityRoles(dir)

	cycleNum := nextCycleNumber(dir)
	outPath := filepath.Join(dir, fmt.Sprintf("metabolism_cycle%d.go", cycleNum))

	var sections []string
	sections = append(sections, fmt.Sprintf("package winze\n\n"+
		"// Metabolism cycle %d: trip-promoted speculative connections.\n"+
		"//\n"+
		"// These claims were generated by the REM-like trip cycle, which picks\n"+
		"// entity pairs from different topology clusters and asks an LLM to\n"+
		"// generate speculative relationships. Only connections scoring 4+/5\n"+
		"// are promoted. Provenance is marked as speculative.\n",
		cycleNum))

	promoted := 0
	var promotedVars []string
	var promotedClaims []promotedClaim
	var attempts []tripPromotionAttempt
	for _, c := range promotable {
		attemptName := fmt.Sprintf("%s_%s_%s", c.EntityA, c.Predicate, c.EntityB)

		// Defensive guard: reject attribution predicates regardless of how
		// they got past the prompt filter (LLM ignored the menu, model
		// changed, prompt regressed). The trip cycle has no source-grounding
		// step, so promoting attribution claims = mirror-source-commitments
		// violation. See tripBannedPredicates.
		if tripBannedPredicates[c.Predicate] {
			evidence := fmt.Sprintf("%s %s %s: predicate %q is attribution-laden; trip cannot supply source grounding",
				c.EntityA, c.Predicate, c.EntityB, c.Predicate)
			fmt.Printf("[trip-promote] skip %s\n", evidence)
			attempts = append(attempts, tripPromotionAttempt{
				Name:     attemptName,
				Accepted: false,
				Reason:   "attribution_predicate_banned",
				Evidence: evidence,
			})
			continue
		}

		// Validate both entities exist
		if !entityVars[c.EntityA] || !entityVars[c.EntityB] {
			evidence := fmt.Sprintf("%s ↔ %s: entity not found in KB", c.EntityA, c.EntityB)
			fmt.Printf("[trip-promote] skip %s\n", evidence)
			attempts = append(attempts, tripPromotionAttempt{
				Name:     attemptName,
				Accepted: false,
				Reason:   "entity_not_found",
				Evidence: evidence,
			})
			continue
		}

		// Determine Subject/Object direction from LLM's SUBJECT response
		subj, obj := c.EntityA, c.EntityB
		if strings.Contains(strings.ToUpper(c.Subject), "B") {
			subj, obj = c.EntityB, c.EntityA
		}

		// Validate predicate type constraints. If the LLM picked the wrong
		// direction, try the swap. If neither orientation satisfies the
		// predicate's slot types, skip the claim — don't write it to disk.
		subjRole, objRole := entityRoles[subj], entityRoles[obj]
		if !validatePredicate(c.Predicate, subjRole, objRole) {
			if validatePredicate(c.Predicate, objRole, subjRole) {
				subj, obj = obj, subj
				subjRole, objRole = objRole, subjRole
			} else {
				evidence := fmt.Sprintf("%s(%s) %s %s(%s): neither orientation satisfies predicate slots",
					c.EntityA, entityRoles[c.EntityA], c.Predicate, c.EntityB, entityRoles[c.EntityB])
				fmt.Printf("[trip-promote] skip %s\n", evidence)
				attempts = append(attempts, tripPromotionAttempt{
					Name:     attemptName,
					Accepted: false,
					Reason:   "type_mismatch",
					Evidence: evidence,
				})
				continue
			}
		}

		provVar := fmt.Sprintf("tripCycle%d%s%sSource", cycleNum, subj, obj)
		claimVar := fmt.Sprintf("TripCycle%d%s%s%s", cycleNum, subj, c.Predicate, obj)

		var b strings.Builder
		b.WriteString(fmt.Sprintf("// ---------------------------------------------------------------------------\n"))
		b.WriteString(fmt.Sprintf("// Trip connection: %s ↔ %s (score %d/5, %s)\n", subj, obj, c.Score, c.PromptType))
		b.WriteString(fmt.Sprintf("// %s\n", c.Connection))
		b.WriteString(fmt.Sprintf("// ---------------------------------------------------------------------------\n\n"))

		b.WriteString(fmt.Sprintf("var %s = Provenance{\n", provVar))
		b.WriteString(fmt.Sprintf("\tOrigin:     \"winze trip cycle %d (speculative cross-cluster connection)\",\n", cycleNum))
		b.WriteString(fmt.Sprintf("\tIngestedAt: %q,\n", time.Now().Format("2006-01-02")))
		b.WriteString(fmt.Sprintf("\tIngestedBy: \"winze metabolism trip (score %d/5, %s, temp=%.1f)\",\n", c.Score, c.PromptType, c.Temperature))
		b.WriteString(fmt.Sprintf("\tQuote:      %q,\n", cleanLLMString(c.Connection+" "+c.Rationale)))
		b.WriteString("}\n\n")

		b.WriteString(fmt.Sprintf("var %s = %s{\n", claimVar, c.Predicate))
		b.WriteString(fmt.Sprintf("\tSubject: %s,\n", subj))
		b.WriteString(fmt.Sprintf("\tObject:  %s,\n", obj))
		b.WriteString(fmt.Sprintf("\tProv:    %s,\n", provVar))
		b.WriteString("}\n")

		sections = append(sections, b.String())
		promoted++
		promotedVars = append(promotedVars, claimVar)
		promotedClaims = append(promotedClaims, promotedClaim{
			VarName:   claimVar,
			Subject:   subj,
			Predicate: c.Predicate,
			Object:    obj,
		})
		attempts = append(attempts, tripPromotionAttempt{
			Name:     claimVar,
			Accepted: true,
			Reason:   "accepted",
			Evidence: fmt.Sprintf("%s %s %s (score %d/5)", subj, c.Predicate, obj, c.Score),
		})
	}

	// Log the promotion funnel regardless of whether any survived.
	// Visibility into entity_not_found / type_mismatch skip reasons is
	// what lets us see *why* promotion rates are low.
	if len(attempts) > 0 {
		if err := logTripPromotionAttempts(dir, attempts); err != nil {
			fmt.Fprintf(os.Stderr, "[trip-promote] log promotion attempts: %v\n", err)
		}
	}

	if promoted == 0 {
		fmt.Println("[trip-promote] no valid connections to promote (entities not found)")
		return nil
	}

	content := strings.Join(sections, "\n")
	if err := os.WriteFile(outPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}

	// Quality gates
	fmt.Printf("[trip-promote] wrote %d claims to %s, validating...\n", promoted, filepath.Base(outPath))
	if !runGate(dir, "go", "build", "./...") {
		fmt.Fprintf(os.Stderr, "[trip-promote] build failed — removing %s\n", filepath.Base(outPath))
		os.Remove(outPath)
		return fmt.Errorf("build failed on trip-promoted claims")
	}
	fmt.Printf("[trip-promote] ✓ %d speculative connections promoted to corpus\n", promoted)

	// Resolve each promoted var against cmd/lint and log as a
	// trip_lint_durability prediction cycle. Non-fatal if resolution
	// fails — the claims are already in the corpus.
	if err := logTripLintDurability(dir, promotedVars); err != nil {
		fmt.Fprintf(os.Stderr, "[trip-promote] lint-durability resolution: %v\n", err)
	}
	// Deterministic //winze:functional collision check. No LLM, no API
	// cost; pure type-system property pinned to a pragma the corpus
	// controls. Runs even when ANTHROPIC_API_KEY is absent.
	if err := logTripFunctionalDurability(dir, promotedClaims); err != nil {
		fmt.Fprintf(os.Stderr, "[trip-promote] functional-durability resolution: %v\n", err)
	}
	// Stricter semantic check via LLM contradiction on the promoted
	// claim's neighborhood. Gated on ANTHROPIC_API_KEY inside the
	// resolver; silently skipped otherwise.
	if err := logTripLLMDurability(dir, promotedClaims); err != nil {
		fmt.Fprintf(os.Stderr, "[trip-promote] llm-durability resolution: %v\n", err)
	}
	return nil
}

// collectEntityRoles returns name → role type for every KB entity. Used by
// trip promotion to validate predicate Subject/Object type constraints.
func collectEntityRoles(dir string) map[string]string {
	out := map[string]string{}
	for _, e := range collectTripEntities(dir) {
		out[e.name] = e.roleType
	}
	return out
}

// collectEntityVarNames returns a set of all entity variable names in the KB.
func collectEntityVarNames(dir string) map[string]bool {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return strings.HasSuffix(fi.Name(), ".go") && !strings.HasSuffix(fi.Name(), "_test.go")
	}, 0)
	if err != nil {
		return nil
	}

	vars := map[string]bool{}
	for _, pkg := range pkgs {
		for _, f := range pkg.Files {
			for _, d := range f.Decls {
				gd, ok := d.(*ast.GenDecl)
				if !ok {
					continue
				}
				for _, s := range gd.Specs {
					vs, ok := s.(*ast.ValueSpec)
					if !ok {
						continue
					}
					for _, name := range vs.Names {
						vars[name.Name] = true
					}
				}
			}
		}
	}
	return vars
}

// collectTripEntities parses KB entities and assigns cluster IDs via BFS.
func collectTripEntities(dir string) []tripEntity {
	var entities []tripRawEntity
	var claims []tripRawClaim

	client, err := defndb.New(dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "[trip] defndb: %v\n", err)
		return nil
	}
	defer client.Close()
	entities, claims, err = collectTripDataDefn(client)
	if err != nil {
		fmt.Fprintf(os.Stderr, "[trip] defndb data: %v\n", err)
		return nil
	}

	// Build adjacency and BFS for clusters (always in-memory).
	adj := map[string]map[string]bool{}
	addEdge := func(a, b string) {
		if adj[a] == nil {
			adj[a] = map[string]bool{}
		}
		if adj[b] == nil {
			adj[b] = map[string]bool{}
		}
		adj[a][b] = true
		adj[b][a] = true
	}
	for _, c := range claims {
		addEdge(c.subject, c.object)
	}

	// BFS cluster assignment
	clusterOf := map[string]int{}
	clusterID := 0
	visited := map[string]bool{}

	for _, e := range entities {
		if visited[e.name] || adj[e.name] == nil {
			continue
		}
		queue := []string{e.name}
		visited[e.name] = true
		for len(queue) > 0 {
			cur := queue[0]
			queue = queue[1:]
			clusterOf[cur] = clusterID
			for neighbor := range adj[cur] {
				if !visited[neighbor] {
					visited[neighbor] = true
					queue = append(queue, neighbor)
				}
			}
		}
		clusterID++
	}

	// Build output, excluding reified meta-hypotheses. Reified entities
	// (TripPromotionSurvivesLint, EvidenceSearchXxx, etc., declared in
	// predictions.go) are loop artifacts of the metabolism's own
	// self-reporting; treating them as candidate trip subjects produces
	// recursive amplification — speculative claims about the substrate's
	// own meta-claims, which the substrate then reifies into more
	// meta-claims. Cycle 4's "TripPromotionPassesContradictionCheck
	// TheoryOf UDHR1948" is the case study for why we filter here.
	var result []tripEntity
	for _, e := range entities {
		if isReifiedEntityFile(e.file) {
			continue
		}
		cid, ok := clusterOf[e.name]
		if !ok {
			cid = -1 // isolated
		}
		result = append(result, tripEntity{
			name:     e.name,
			roleType: e.roleType,
			brief:    e.brief,
			file:     e.file,
			cluster:  cid,
		})
	}
	return result
}

// isReifiedEntityFile reports whether a corpus file holds reify-output
// entities (meta-hypotheses, EvidenceSearch events, ResolutionOutcome
// vars). Trip pair selection excludes these — see the comment in
// collectTripEntities.
func isReifiedEntityFile(file string) bool {
	return file == "predictions.go"
}

// tripRawEntity and tripRawClaim are used by both defn and AST data collection.
type tripRawEntity = struct {
	name     string
	roleType string
	brief    string
	file     string
}

type tripRawClaim = struct {
	subject string
	object  string
}

func collectTripDataDefn(client *defndb.Client) ([]tripRawEntity, []tripRawClaim, error) {
	// Get var-to-role-type mapping
	varRoles, err := client.EntityVarsWithRoles()
	if err != nil {
		return nil, nil, err
	}
	varRoleMap := map[string]string{}
	varFileMap := map[string]string{}
	for _, vr := range varRoles {
		base := filepath.Base(vr.SourceFile)
		if isInfraFile(base) {
			continue
		}
		varRoleMap[vr.VarName] = vr.RoleType
		varFileMap[vr.VarName] = base
	}

	// Entity fields (for Brief)
	eFields, err := client.EntityFields()
	if err != nil {
		return nil, nil, err
	}
	type eBuild struct {
		name, roleType, brief, file string
	}
	em := map[string]*eBuild{}
	for _, f := range eFields {
		rt, ok := varRoleMap[f.DefName]
		if !ok {
			continue
		}
		eb, ok := em[f.DefName]
		if !ok {
			eb = &eBuild{name: f.DefName, roleType: rt, file: varFileMap[f.DefName]}
			em[f.DefName] = eb
		}
		if f.FieldName == "Brief" {
			eb.brief = strings.Trim(f.FieldValue, "\"")
		}
	}
	// Also add entities that have no Name/Brief fields
	for varName, rt := range varRoleMap {
		if _, ok := em[varName]; !ok {
			em[varName] = &eBuild{name: varName, roleType: rt, file: varFileMap[varName]}
		}
	}
	entities := make([]tripRawEntity, 0, len(em))
	for _, eb := range em {
		entities = append(entities, tripRawEntity{name: eb.name, roleType: eb.roleType, brief: eb.brief, file: eb.file})
	}

	// Claim fields
	cFields, err := client.ClaimFields()
	if err != nil {
		return nil, nil, err
	}
	type cBuild struct {
		subject, object string
	}
	cm := map[string]*cBuild{}
	for _, f := range cFields {
		c, ok := cm[f.DefName]
		if !ok {
			c = &cBuild{}
			cm[f.DefName] = c
		}
		val := strings.Trim(f.FieldValue, "\"")
		switch f.FieldName {
		case "Subject":
			c.subject = val
		case "Object":
			c.object = val
		}
	}
	var claims []tripRawClaim
	for _, c := range cm {
		if c.subject != "" && c.object != "" {
			claims = append(claims, tripRawClaim{subject: c.subject, object: c.object})
		}
	}

	return entities, claims, nil
}


// pickCrossClusterPairs selects entity pairs from different clusters.
// Prioritizes pairs where both entities have Briefs (for better LLM context).
func pickCrossClusterPairs(entities []tripEntity, n int) []tripPair {
	// Group by cluster
	byCluster := map[int][]tripEntity{}
	for _, e := range entities {
		if e.cluster >= 0 {
			byCluster[e.cluster] = append(byCluster[e.cluster], e)
		}
	}

	clusterIDs := make([]int, 0, len(byCluster))
	for id := range byCluster {
		clusterIDs = append(clusterIDs, id)
	}
	sort.Ints(clusterIDs)

	if len(clusterIDs) < 2 {
		return nil
	}

	// Generate candidate pairs from different clusters
	type candidate struct {
		pair  tripPair
		score int // both have briefs = 2, one has = 1, neither = 0
	}
	var candidates []candidate

	for i, cidA := range clusterIDs {
		for _, cidB := range clusterIDs[i+1:] {
			for _, a := range byCluster[cidA] {
				for _, b := range byCluster[cidB] {
					s := 0
					if a.brief != "" {
						s++
					}
					if b.brief != "" {
						s++
					}
					candidates = append(candidates, candidate{
						pair:  tripPair{A: a, B: b},
						score: s,
					})
				}
			}
		}
	}

	// Shuffle, then sort by score (both-have-briefs first)
	rand.Shuffle(len(candidates), func(i, j int) {
		candidates[i], candidates[j] = candidates[j], candidates[i]
	})
	sort.SliceStable(candidates, func(i, j int) bool {
		return candidates[i].score > candidates[j].score
	})

	// Take top n
	if n > len(candidates) {
		n = len(candidates)
	}
	pairs := make([]tripPair, n)
	for i := 0; i < n; i++ {
		pairs[i] = candidates[i].pair
	}
	return pairs
}

type weightedEntity struct {
	entity tripEntity
	weight float64
}

// pickEntityGroups selects groups of entities for confluence/synthesis modes.
// Implements REBUS-like flattened priors: entities are weighted inversely by
// their claim count (thin entities are MORE likely to be selected, not less).
// If includeIsolates is true (synthesis mode), entities with no cluster
// assignment (cluster -1) are included — the entropic brain effect.
func pickEntityGroups(entities []tripEntity, nGroups int, groupSize int, includeIsolates bool) []tripGroup {
	var pool []tripEntity
	for _, e := range entities {
		if !includeIsolates && e.cluster < 0 {
			continue
		}
		pool = append(pool, e)
	}

	if len(pool) < groupSize {
		return nil
	}

	// REBUS weighting: thin/peripheral entities get boosted rather than
	// penalized (opposite of pickCrossClusterPairs).
	var wpool []weightedEntity
	for _, e := range pool {
		w := 1.0
		if e.brief == "" {
			w = 2.0 // thin entities are more interesting, not less
		}
		wpool = append(wpool, weightedEntity{entity: e, weight: w})
	}

	var groups []tripGroup
	for i := 0; i < nGroups; i++ {
		g := pickWeightedGroup(wpool, groupSize)
		if g == nil {
			continue
		}
		groups = append(groups, tripGroup{Entities: g})
	}
	return groups
}

// pickWeightedGroup selects groupSize entities with weighted random sampling
// (without replacement within a single group). Different groups may share entities.
func pickWeightedGroup(pool []weightedEntity, groupSize int) []tripEntity {
	if len(pool) < groupSize {
		return nil
	}

	// Build cumulative weights
	totalWeight := 0.0
	for _, w := range pool {
		totalWeight += w.weight
	}

	selected := make(map[int]bool)
	var result []tripEntity

	for len(result) < groupSize {
		r := rand.Float64() * totalWeight
		cumulative := 0.0
		for idx, w := range pool {
			if selected[idx] {
				continue
			}
			cumulative += w.weight
			if cumulative >= r {
				selected[idx] = true
				result = append(result, w.entity)
				totalWeight -= w.weight
				break
			}
		}
	}
	return result
}

// generateGroupConnection calls the LLM to generate a narrative connection
// for a group of 3-5 entities (confluence/synthesis modes). Uses a two-pass
// approach: first generate the narrative, then score it separately.
func generateGroupConnection(client anthropic.Client, group tripGroup, promptType string, temperature float64) (TripConnection, error) {
	prompt := buildGroupPrompt(group, promptType)

	maxTokens := int64(1024)
	if promptType == "synthesis" {
		maxTokens = 2048
	}

	// Pass 1: generate narrative
	// Anthropic API caps temperature at 1.0 — clamp for the API call while
	// preserving the user-facing 0-1.5 scale for drug profile labeling.
	apiTemp := temperature
	if apiTemp > 1.0 {
		apiTemp = 1.0
	}
	resp, err := client.Messages.New(context.Background(), anthropic.MessageNewParams{
		Model:       anthropic.ModelClaudeSonnet4_5,
		MaxTokens:   maxTokens,
		Temperature: anthropic.Float(apiTemp),
		Messages: []anthropic.MessageParam{
			anthropic.NewUserMessage(anthropic.NewTextBlock(prompt)),
		},
	})
	if err != nil {
		return TripConnection{}, fmt.Errorf("API error: %w", err)
	}

	var narrative string
	for _, block := range resp.Content {
		if block.Type == "text" {
			narrative = block.Text
			break
		}
	}

	// Extract new concept name for synthesis mode
	var newConcept string
	if promptType == "synthesis" {
		newConcept = extractNewConcept(narrative)
	}

	// Build entity name list
	names := make([]string, len(group.Entities))
	for i, e := range group.Entities {
		names[i] = e.name
	}

	// Pass 2: score the narrative
	score, rationale := scoreNarrative(client, names, narrative, promptType)

	// Extract a one-line summary for Connection field
	connection := extractFirstSentence(narrative)

	conn := TripConnection{
		EntityA:     names[0],
		EntityB:     names[1],
		Entities:    names,
		GroupSize:   len(names),
		PromptType:  promptType,
		Temperature: temperature,
		Connection:  connection,
		Narrative:   narrative,
		NewConcept:  newConcept,
		Score:       score,
		Rationale:   rationale,
	}
	if len(group.Entities) > 0 {
		conn.ClusterA = group.Entities[0].cluster
	}
	if len(group.Entities) > 1 {
		conn.ClusterB = group.Entities[1].cluster
	}
	return conn, nil
}

func buildGroupPrompt(group tripGroup, promptType string) string {
	var b strings.Builder

	b.WriteString("You are generating speculative connections for a knowledge base about the epistemology of minds — how minds build, validate, and fail at modeling reality.\n\n")

	switch promptType {
	case "confluence":
		b.WriteString("MODE: CONFLUENCE\n")
		b.WriteString("These entities have no known connection. Your task: write a short narrative (~150 words) ")
		b.WriteString("about how they are secretly aspects of the same deeper phenomenon. ")
		b.WriteString("Not surface-level analogy — find the structural convergence. ")
		b.WriteString("What is the hidden stream they all flow into?\n\n")
	case "synthesis":
		b.WriteString("MODE: SYNTHESIS\n")
		b.WriteString("These entities are unconnected fragments. Your task: discover the concept they imply ")
		b.WriteString("when considered together — something the knowledge base doesn't have yet. ")
		b.WriteString("Write a narrative (~200 words) that builds toward naming this new concept. ")
		b.WriteString("End with a line: NEW CONCEPT: <name> — <one sentence definition>\n\n")
	}

	b.WriteString("Entities:\n\n")
	for i, e := range group.Entities {
		brief := e.brief
		if brief == "" {
			brief = "(no description — peripheral entity, underexplored)"
		}
		b.WriteString(fmt.Sprintf("  %d. %s (%s)\n     %s\n\n", i+1, e.name, e.roleType, brief))
	}

	b.WriteString("Write freely. No structured format required — just the narrative")
	if promptType == "synthesis" {
		b.WriteString(", ending with the NEW CONCEPT line")
	}
	b.WriteString(".\n")

	return b.String()
}

// scoreNarrative uses a separate LLM call to judge a narrative connection.
// Lower temperature, different model — the critic should be sober.
func scoreNarrative(client anthropic.Client, entityNames []string, narrative string, promptType string) (int, string) {
	prompt := fmt.Sprintf(`Score this speculative %s narrative from a knowledge base trip cycle.

Entities involved: %s

Narrative:
%s

Score 1-5:
  1 = trivial or forced connection
  2 = surface-level, wouldn't survive scrutiny
  3 = interesting, worth remembering
  4 = novel and defensible — changes how you think about the entities
  5 = genuinely surprising — this should be in the KB

Call score_narrative with your score and one-sentence rationale.`, promptType, strings.Join(entityNames, ", "), narrative)

	schema := anthropic.ToolInputSchemaParam{
		Properties: map[string]any{
			"score": map[string]any{
				"type":        "integer",
				"minimum":     1,
				"maximum":     5,
				"description": "1=trivial, 2=weak, 3=interesting, 4=novel+defensible, 5=genuinely surprising.",
			},
			"rationale": map[string]any{
				"type":        "string",
				"description": "One sentence explaining the score.",
			},
		},
		Required: []string{"score", "rationale"},
	}
	tool := anthropic.ToolUnionParamOfTool(schema, "score_narrative")

	raw, err := callToolUse(client, prompt, tool, anthropic.ModelClaudeHaiku4_5, 0.0, 128)
	if err != nil {
		return 1, "scoring failed"
	}
	var out struct {
		Score     int    `json:"score"`
		Rationale string `json:"rationale"`
	}
	if err := json.Unmarshal(raw, &out); err != nil {
		return 1, "decode failed"
	}
	return out.Score, out.Rationale
}

// extractNewConcept pulls the NEW CONCEPT line from a synthesis narrative.
func extractNewConcept(narrative string) string {
	for _, line := range strings.Split(narrative, "\n") {
		line = strings.TrimSpace(line)
		if v, ok := strings.CutPrefix(line, "NEW CONCEPT:"); ok {
			return strings.TrimSpace(v)
		}
	}
	return ""
}

// extractFirstSentence returns the first sentence of a narrative for the Connection field.
func extractFirstSentence(s string) string {
	s = strings.TrimSpace(s)
	for i, c := range s {
		if c == '.' || c == '!' || c == '?' {
			if i+1 < len(s) {
				return s[:i+1]
			}
		}
	}
	if len(s) > 200 {
		return s[:200] + "..."
	}
	return s
}

// callToolUse invokes the API with a single forced tool and returns the Input
// JSON. The model cannot free-form — it must emit tool_use with schema-valid
// input, eliminating parse failures and invalid enums by construction.
func callToolUse(client anthropic.Client, prompt string, tool anthropic.ToolUnionParam, model anthropic.Model, temp float64, maxTokens int64) (json.RawMessage, error) {
	resp, err := client.Messages.New(context.Background(), anthropic.MessageNewParams{
		Model:       model,
		MaxTokens:   maxTokens,
		Temperature: anthropic.Float(temp),
		Tools:       []anthropic.ToolUnionParam{tool},
		ToolChoice:  anthropic.ToolChoiceParamOfTool(tool.OfTool.Name),
		Messages: []anthropic.MessageParam{
			anthropic.NewUserMessage(anthropic.NewTextBlock(prompt)),
		},
	})
	if err != nil {
		return nil, fmt.Errorf("API error: %w", err)
	}
	for _, block := range resp.Content {
		if block.Type == "tool_use" {
			tu := block.AsToolUse()
			return tu.Input, nil
		}
	}
	return nil, fmt.Errorf("no tool_use block in response")
}

// generateConnection calls the LLM to generate and judge a speculative connection.
// Uses tool_use with a dynamically-scoped predicate enum: only predicates whose
// Subject/Object slots could accept this entity pair are offered. Invalid
// predicates are impossible by schema.
func generateConnection(client anthropic.Client, pair tripPair, promptType string, temperature float64) (TripConnection, error) {
	prompt := buildTripPrompt(pair, promptType)

	apiTemp := temperature
	if apiTemp > 1.0 {
		apiTemp = 1.0
	}

	// Build a per-pair predicate enum. If empty, allow NONE only.
	// Attribution predicates are filtered out — see tripBannedPredicates.
	compat := tripCompatiblePredicates(pair.A.roleType, pair.B.roleType)
	predEnum := append([]string{"NONE"}, compat...)

	schema := anthropic.ToolInputSchemaParam{
		Properties: map[string]any{
			"connection": map[string]any{
				"type":        "string",
				"description": "One sentence describing the speculative connection.",
			},
			"predicate": map[string]any{
				"type":        "string",
				"enum":        predEnum,
				"description": "Which KB predicate fits. NONE if no compatible predicate.",
			},
			"subject": map[string]any{
				"type":        "string",
				"enum":        []string{"A", "B"},
				"description": "Which entity is the predicate Subject.",
			},
			"score": map[string]any{
				"type":        "integer",
				"minimum":     1,
				"maximum":     5,
				"description": "1=trivial, 2=weak, 3=interesting, 4=novel+defensible, 5=genuinely surprising.",
			},
			"rationale": map[string]any{
				"type":        "string",
				"description": "One sentence explaining the score.",
			},
		},
		Required: []string{"connection", "predicate", "subject", "score", "rationale"},
	}
	tool := anthropic.ToolUnionParamOfTool(schema, "propose_connection")

	raw, err := callToolUse(client, prompt, tool, anthropic.ModelClaudeHaiku4_5, apiTemp, 512)
	if err != nil {
		return TripConnection{}, err
	}

	var out struct {
		Connection string `json:"connection"`
		Predicate  string `json:"predicate"`
		Subject    string `json:"subject"`
		Score      int    `json:"score"`
		Rationale  string `json:"rationale"`
	}
	if err := json.Unmarshal(raw, &out); err != nil {
		return TripConnection{}, fmt.Errorf("decode tool input: %w", err)
	}

	conn := TripConnection{
		EntityA:     pair.A.name,
		EntityB:     pair.B.name,
		ClusterA:    pair.A.cluster,
		ClusterB:    pair.B.cluster,
		PromptType:  promptType,
		Temperature: temperature,
		Connection:  out.Connection,
		Rationale:   out.Rationale,
		Subject:     out.Subject,
		Score:       out.Score,
	}
	if out.Predicate != "NONE" {
		conn.Predicate = out.Predicate
	}
	return conn, nil
}

func buildTripPrompt(pair tripPair, promptType string) string {
	var promptInstruction string
	switch promptType {
	case "analogy":
		promptInstruction = "How is entity A structurally, functionally, or conceptually similar to entity B? What shared pattern connects them despite belonging to different domains?"
	case "contradiction":
		promptInstruction = "How might entity A's claims undermine, challenge, or contradict entity B's claims? What tension exists between them?"
	case "genealogy":
		promptInstruction = "Could entity A have historically influenced entity B, or vice versa? Is there a causal, intellectual, or genealogical link?"
	case "prediction":
		promptInstruction = "If entity A's claims are true, what does that specifically imply for entity B? Generate a falsifiable prediction."
	}

	briefA := pair.A.brief
	if briefA == "" {
		briefA = "(no description available)"
	}
	briefB := pair.B.brief
	if briefB == "" {
		briefB = "(no description available)"
	}

	// Filter predicate table to only those compatible with this pair's
	// roles, minus attribution predicates (tripBannedPredicates) which the
	// promoter would refuse anyway. Showing them would just waste tokens.
	compat := tripCompatiblePredicates(pair.A.roleType, pair.B.roleType)
	var predicateList string
	if len(compat) == 0 {
		predicateList = "  (no compatible predicates for this role pair — use NONE)"
	} else {
		var b strings.Builder
		for _, p := range compat {
			s := predicateSlots[p]
			b.WriteString(fmt.Sprintf("  %s: %s→%s\n", p, s.Subject, s.Object))
		}
		predicateList = b.String()
	}

	return fmt.Sprintf(`You are generating speculative cross-domain connections for a knowledge base about the epistemology of minds — how minds build, validate, and fail at modeling reality.

These two entities are in DIFFERENT clusters (no existing connection). Your job: find a non-obvious but defensible connection.

Entity A: %s (%s)
  %s

Entity B: %s (%s)
  %s

Connection type: %s
%s

Compatible predicates for this entity pair (Subject→Object):
%s
Entity A is a %s. Entity B is a %s. Use only a predicate from the list above (or NONE). SUBJECT must match the predicate's Subject role. If no meaningful connection exists, set predicate=NONE and score=1.`,
		pair.A.name, pair.A.roleType, briefA,
		pair.B.name, pair.B.roleType, briefB,
		promptType, promptInstruction,
		predicateList,
		pair.A.roleType, pair.B.roleType)
}

// drugProfile characterizes the temperature × prompt combination.
func drugProfile(temperature float64, promptType string) string {
	var tempLabel string
	switch {
	case temperature >= 0.9:
		tempLabel = "psychedelic"
	case temperature >= 0.6:
		tempLabel = "exploratory"
	case temperature >= 0.3:
		tempLabel = "microdose"
	default:
		tempLabel = "sober"
	}

	var promptLabel string
	switch promptType {
	case "analogy":
		promptLabel = "pattern-matching"
	case "contradiction":
		promptLabel = "adversarial"
	case "genealogy":
		promptLabel = "causal-tracing"
	case "prediction":
		promptLabel = "forecasting"
	case "confluence":
		promptLabel = "convergence"
	case "synthesis":
		promptLabel = "concept-genesis"
	}

	return tempLabel + "/" + promptLabel
}
