// Trip cycle: REM-like speculative cross-cluster connection generation.
//
// Deliberately over-connects — picks entity pairs from different topology
// clusters and asks an LLM to generate speculative relationships. A second
// LLM pass judges interestingness. Interesting connections become candidate
// claims for human or pipeline review.
//
// Two orthogonal axes:
//   - Temperature: wildness of connection (0.0 conservative, 1.5 psychedelic)
//   - Prompt type: kind of connection (analogy, contradiction, genealogy, prediction)
//
// Together they form a "drug profile" for each trip cycle run.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"math/rand"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/anthropics/anthropic-sdk-go"
	"github.com/anthropics/anthropic-sdk-go/option"
	"github.com/justinstimatze/winze/internal/astutil"
	"github.com/justinstimatze/winze/internal/defndb"
)

// --- trip types ---

type tripEntity struct {
	name     string
	roleType string
	brief    string
	file     string
	cluster  int
}

type tripPair struct {
	A tripEntity
	B tripEntity
}

// TripConnection is a speculative connection generated by the trip cycle.
type TripConnection struct {
	EntityA     string  `json:"entity_a"`
	EntityB     string  `json:"entity_b"`
	ClusterA    int     `json:"cluster_a"`
	ClusterB    int     `json:"cluster_b"`
	PromptType  string  `json:"prompt_type"`
	Temperature float64 `json:"temperature"`
	Connection  string  `json:"connection"`
	Predicate   string  `json:"predicate,omitempty"`
	Score       int     `json:"score"` // 1-5 interestingness
	Rationale   string  `json:"rationale"`
}

type TripReport struct {
	Pairs       int              `json:"pairs_evaluated"`
	Connections []TripConnection `json:"connections"`
	DrugProfile string           `json:"drug_profile"`
	Temperature float64          `json:"temperature"`
	PromptType  string           `json:"prompt_type"`
}

func runTrip(dir string, temperature float64, promptType string, nPairs int, dryRun bool, jsonOut bool) TripReport {
	validPrompts := map[string]bool{"analogy": true, "contradiction": true, "genealogy": true, "prediction": true}
	if !validPrompts[promptType] {
		fmt.Fprintf(os.Stderr, "trip: --prompt-type must be analogy, contradiction, genealogy, or prediction (got %q)\n", promptType)
		os.Exit(1)
	}
	if temperature < 0 || temperature > 1.5 {
		fmt.Fprintf(os.Stderr, "trip: --temperature must be 0.0-1.5 (got %.1f)\n", temperature)
		os.Exit(1)
	}

	// Characterize the drug profile
	profile := drugProfile(temperature, promptType)

	// 1. Collect entities with cluster membership
	entities := collectTripEntities(dir)
	if len(entities) == 0 {
		fmt.Println("[trip] no entities found")
		return TripReport{}
	}

	// Count clusters
	clusterSet := map[int]bool{}
	for _, e := range entities {
		clusterSet[e.cluster] = true
	}

	fmt.Printf("[trip] %d entities, %d clusters — profile: %s (temp=%.1f, prompt=%s)\n",
		len(entities), len(clusterSet), profile, temperature, promptType)

	// 2. Pick cross-cluster pairs
	pairs := pickCrossClusterPairs(entities, nPairs)
	if len(pairs) == 0 {
		fmt.Println("[trip] no cross-cluster pairs possible (all entities in one cluster?)")
		return TripReport{}
	}

	fmt.Printf("[trip] selected %d cross-cluster pairs\n", len(pairs))

	if dryRun {
		fmt.Println("\n  dry run — would evaluate:")
		for _, p := range pairs {
			fmt.Printf("    [%d] %-30s ↔ [%d] %-30s\n",
				p.A.cluster, p.A.name, p.B.cluster, p.B.name)
		}
		return TripReport{Pairs: len(pairs), DrugProfile: profile, Temperature: temperature, PromptType: promptType}
	}

	// 3. LLM: generate + judge connections
	loadDotEnv(dir)
	apiKey := os.Getenv("ANTHROPIC_API_KEY")
	if apiKey == "" {
		fmt.Fprintf(os.Stderr, "[trip] ANTHROPIC_API_KEY required\n")
		os.Exit(1)
	}
	client := anthropic.NewClient(option.WithAPIKey(apiKey))

	var connections []TripConnection
	for i, p := range pairs {
		fmt.Printf("  [%d/%d] %s ↔ %s ... ", i+1, len(pairs), p.A.name, p.B.name)

		conn, err := generateConnection(client, p, promptType, temperature)
		if err != nil {
			fmt.Printf("error: %v\n", err)
			continue
		}
		connections = append(connections, conn)

		marker := "·"
		if conn.Score >= 4 {
			marker = "!"
		} else if conn.Score >= 3 {
			marker = "*"
		}
		fmt.Printf("%s score=%d\n", marker, conn.Score)
	}

	report := TripReport{
		Pairs:       len(pairs),
		Connections: connections,
		DrugProfile: profile,
		Temperature: temperature,
		PromptType:  promptType,
	}

	if jsonOut {
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		if err := enc.Encode(report); err != nil {
			fmt.Fprintf(os.Stderr, "trip: JSON encode: %v\n", err)
		}
		return report
	}

	// Text output
	fmt.Printf("\n[trip] %d connections generated\n\n", len(connections))

	// Sort by score descending
	sort.Slice(connections, func(i, j int) bool {
		return connections[i].Score > connections[j].Score
	})

	for _, c := range connections {
		marker := " "
		switch {
		case c.Score >= 4:
			marker = "!"
		case c.Score >= 3:
			marker = "*"
		default:
			marker = "·"
		}
		fmt.Printf("  %s [%d/5] %s ↔ %s\n", marker, c.Score, c.EntityA, c.EntityB)
		fmt.Printf("          %s\n", c.Connection)
		if c.Predicate != "" {
			fmt.Printf("          predicate: %s\n", c.Predicate)
		}
		fmt.Printf("          rationale: %s\n\n", c.Rationale)
	}

	// Summary
	interesting := 0
	for _, c := range connections {
		if c.Score >= 3 {
			interesting++
		}
	}
	fmt.Printf("[trip] %d/%d connections scored >= 3 (interesting)\n", interesting, len(connections))
	fmt.Println("  legend: ! score 4-5 (promote)  * score 3 (review)  · score 1-2 (drop)")
	return report
}

// promoteConnections converts high-scoring trip connections into corpus claims.
// Only promotes connections with Score >= 4, a valid predicate, and both entities
// existing in the KB. Writes to a new metabolism_cycleN.go file with quality gates.
func promoteConnections(dir string, connections []TripConnection) error {
	// Filter for promotable connections
	var promotable []TripConnection
	for _, c := range connections {
		if c.Score >= 4 && c.Predicate != "" && c.Predicate != "NONE" {
			promotable = append(promotable, c)
		}
	}
	if len(promotable) == 0 {
		fmt.Println("[trip-promote] no connections scored 4+ with valid predicate")
		return nil
	}

	// Collect existing entity var names to validate
	entityVars := collectEntityVarNames(dir)

	cycleNum := nextCycleNumber(dir)
	outPath := filepath.Join(dir, fmt.Sprintf("metabolism_cycle%d.go", cycleNum))

	var sections []string
	sections = append(sections, fmt.Sprintf("package winze\n\n"+
		"// Metabolism cycle %d: trip-promoted speculative connections.\n"+
		"//\n"+
		"// These claims were generated by the REM-like trip cycle, which picks\n"+
		"// entity pairs from different topology clusters and asks an LLM to\n"+
		"// generate speculative relationships. Only connections scoring 4+/5\n"+
		"// are promoted. Provenance is marked as speculative.\n",
		cycleNum))

	promoted := 0
	for _, c := range promotable {
		// Validate both entities exist
		if !entityVars[c.EntityA] || !entityVars[c.EntityB] {
			fmt.Printf("[trip-promote] skip %s ↔ %s: entity not found in KB\n", c.EntityA, c.EntityB)
			continue
		}

		provVar := fmt.Sprintf("tripCycle%d%s%sSource", cycleNum, c.EntityA, c.EntityB)
		claimVar := fmt.Sprintf("TripCycle%d%s%s%s", cycleNum, c.EntityA, c.Predicate, c.EntityB)

		var b strings.Builder
		b.WriteString(fmt.Sprintf("// ---------------------------------------------------------------------------\n"))
		b.WriteString(fmt.Sprintf("// Trip connection: %s ↔ %s (score %d/5, %s)\n", c.EntityA, c.EntityB, c.Score, c.PromptType))
		b.WriteString(fmt.Sprintf("// %s\n", c.Connection))
		b.WriteString(fmt.Sprintf("// ---------------------------------------------------------------------------\n\n"))

		b.WriteString(fmt.Sprintf("var %s = Provenance{\n", provVar))
		b.WriteString(fmt.Sprintf("\tOrigin:     \"winze trip cycle %d (speculative cross-cluster connection)\",\n", cycleNum))
		b.WriteString(fmt.Sprintf("\tIngestedAt: %q,\n", time.Now().Format("2006-01-02")))
		b.WriteString(fmt.Sprintf("\tIngestedBy: \"winze metabolism trip (score %d/5, %s, temp=%.1f)\",\n", c.Score, c.PromptType, c.Temperature))
		b.WriteString(fmt.Sprintf("\tQuote:      %q,\n", cleanLLMString(c.Connection+" "+c.Rationale)))
		b.WriteString("}\n\n")

		b.WriteString(fmt.Sprintf("var %s = %s{\n", claimVar, c.Predicate))
		b.WriteString(fmt.Sprintf("\tSubject: %s,\n", c.EntityA))
		b.WriteString(fmt.Sprintf("\tObject:  %s,\n", c.EntityB))
		b.WriteString(fmt.Sprintf("\tProv:    %s,\n", provVar))
		b.WriteString("}\n")

		sections = append(sections, b.String())
		promoted++
	}

	if promoted == 0 {
		fmt.Println("[trip-promote] no valid connections to promote (entities not found)")
		return nil
	}

	content := strings.Join(sections, "\n")
	if err := os.WriteFile(outPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}

	// Quality gates
	fmt.Printf("[trip-promote] wrote %d claims to %s, validating...\n", promoted, filepath.Base(outPath))
	if !runGate(dir, "go", "build", "./...") {
		fmt.Fprintf(os.Stderr, "[trip-promote] build failed — removing %s\n", filepath.Base(outPath))
		os.Remove(outPath)
		return fmt.Errorf("build failed on trip-promoted claims")
	}
	fmt.Printf("[trip-promote] ✓ %d speculative connections promoted to corpus\n", promoted)
	return nil
}

// collectEntityVarNames returns a set of all entity variable names in the KB.
func collectEntityVarNames(dir string) map[string]bool {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return strings.HasSuffix(fi.Name(), ".go") && !strings.HasSuffix(fi.Name(), "_test.go")
	}, 0)
	if err != nil {
		return nil
	}

	vars := map[string]bool{}
	for _, pkg := range pkgs {
		for _, f := range pkg.Files {
			for _, d := range f.Decls {
				gd, ok := d.(*ast.GenDecl)
				if !ok {
					continue
				}
				for _, s := range gd.Specs {
					vs, ok := s.(*ast.ValueSpec)
					if !ok {
						continue
					}
					for _, name := range vs.Names {
						vars[name.Name] = true
					}
				}
			}
		}
	}
	return vars
}

// collectTripEntities parses KB entities and assigns cluster IDs via BFS.
func collectTripEntities(dir string) []tripEntity {
	type rawEntity struct {
		name     string
		roleType string
		brief    string
		file     string
	}
	type claim struct {
		subject string
		object  string
	}

	var entities []rawEntity
	var claims []claim

	// Try defndb first for entity + claim collection.
	if client, err := defndb.New(dir); err == nil {
		if ents, cls, err := collectTripDataDefn(client); err == nil {
			entities = ents
			claims = cls
		}
	}

	// AST fallback if defndb didn't produce results.
	if entities == nil {
		var err error
		entities, claims, err = collectTripDataAST(dir)
		if err != nil {
			return nil
		}
	}

	// Build adjacency and BFS for clusters (always in-memory).
	adj := map[string]map[string]bool{}
	addEdge := func(a, b string) {
		if adj[a] == nil {
			adj[a] = map[string]bool{}
		}
		if adj[b] == nil {
			adj[b] = map[string]bool{}
		}
		adj[a][b] = true
		adj[b][a] = true
	}
	for _, c := range claims {
		addEdge(c.subject, c.object)
	}

	// Build adjacency and BFS for clusters.
	// NOTE: This BFS duplicates logic in topology/main.go. The topology tool
	// exports cluster count but not per-entity cluster assignments, so trip
	// must compute its own. If topology ever exports ClusterOf map[string]int,
	// this BFS can be replaced with a cache lookup.
	adj := map[string]map[string]bool{}
	addEdge := func(a, b string) {
		if adj[a] == nil {
			adj[a] = map[string]bool{}
		}
		if adj[b] == nil {
			adj[b] = map[string]bool{}
		}
		adj[a][b] = true
		adj[b][a] = true
	}
	for _, c := range claims {
		addEdge(c.subject, c.object)
	}

	// BFS cluster assignment
	clusterOf := map[string]int{}
	clusterID := 0
	visited := map[string]bool{}

	for _, e := range entities {
		if visited[e.name] || adj[e.name] == nil {
			continue
		}
		queue := []string{e.name}
		visited[e.name] = true
		for len(queue) > 0 {
			cur := queue[0]
			queue = queue[1:]
			clusterOf[cur] = clusterID
			for neighbor := range adj[cur] {
				if !visited[neighbor] {
					visited[neighbor] = true
					queue = append(queue, neighbor)
				}
			}
		}
		clusterID++
	}

	// Build output
	var result []tripEntity
	for _, e := range entities {
		cid, ok := clusterOf[e.name]
		if !ok {
			cid = -1 // isolated
		}
		result = append(result, tripEntity{
			name:     e.name,
			roleType: e.roleType,
			brief:    e.brief,
			file:     e.file,
			cluster:  cid,
		})
	}
	return result
}

// extractClaimEndpoints extracts Subject and Object identifiers from a claim literal.
func extractClaimEndpoints(cl *ast.CompositeLit) (string, string) {
	var subj, obj string
	for _, elt := range cl.Elts {
		kv, ok := elt.(*ast.KeyValueExpr)
		if !ok {
			continue
		}
		key, ok := kv.Key.(*ast.Ident)
		if !ok {
			continue
		}
		switch key.Name {
		case "Subject":
			subj = exprIdent(kv.Value)
		case "Object":
			obj = exprIdent(kv.Value)
		}
	}
	return subj, obj
}

// exprIdent extracts the identifier name from various AST patterns.
func exprIdent(e ast.Expr) string { return astutil.ExprIdent(e) }

// pickCrossClusterPairs selects entity pairs from different clusters.
// Prioritizes pairs where both entities have Briefs (for better LLM context).
func pickCrossClusterPairs(entities []tripEntity, n int) []tripPair {
	// Group by cluster
	byCluster := map[int][]tripEntity{}
	for _, e := range entities {
		if e.cluster >= 0 {
			byCluster[e.cluster] = append(byCluster[e.cluster], e)
		}
	}

	clusterIDs := make([]int, 0, len(byCluster))
	for id := range byCluster {
		clusterIDs = append(clusterIDs, id)
	}
	sort.Ints(clusterIDs)

	if len(clusterIDs) < 2 {
		return nil
	}

	// Generate candidate pairs from different clusters
	type candidate struct {
		pair  tripPair
		score int // both have briefs = 2, one has = 1, neither = 0
	}
	var candidates []candidate

	for i, cidA := range clusterIDs {
		for _, cidB := range clusterIDs[i+1:] {
			for _, a := range byCluster[cidA] {
				for _, b := range byCluster[cidB] {
					s := 0
					if a.brief != "" {
						s++
					}
					if b.brief != "" {
						s++
					}
					candidates = append(candidates, candidate{
						pair:  tripPair{A: a, B: b},
						score: s,
					})
				}
			}
		}
	}

	// Shuffle, then sort by score (both-have-briefs first)
	rand.Shuffle(len(candidates), func(i, j int) {
		candidates[i], candidates[j] = candidates[j], candidates[i]
	})
	sort.SliceStable(candidates, func(i, j int) bool {
		return candidates[i].score > candidates[j].score
	})

	// Take top n
	if n > len(candidates) {
		n = len(candidates)
	}
	pairs := make([]tripPair, n)
	for i := 0; i < n; i++ {
		pairs[i] = candidates[i].pair
	}
	return pairs
}

// generateConnection calls the LLM to generate and judge a speculative connection.
func generateConnection(client anthropic.Client, pair tripPair, promptType string, temperature float64) (TripConnection, error) {
	prompt := buildTripPrompt(pair, promptType)

	resp, err := client.Messages.New(context.Background(), anthropic.MessageNewParams{
		Model:       anthropic.ModelClaudeHaiku4_5,
		MaxTokens:   512,
		Temperature: anthropic.Float(temperature),
		Messages: []anthropic.MessageParam{
			anthropic.NewUserMessage(anthropic.NewTextBlock(prompt)),
		},
	})
	if err != nil {
		return TripConnection{}, fmt.Errorf("API error: %w", err)
	}

	var responseText string
	for _, block := range resp.Content {
		if block.Type == "text" {
			responseText = block.Text
			break
		}
	}

	conn := parseTripResponse(responseText)
	conn.EntityA = pair.A.name
	conn.EntityB = pair.B.name
	conn.ClusterA = pair.A.cluster
	conn.ClusterB = pair.B.cluster
	conn.PromptType = promptType
	conn.Temperature = temperature

	return conn, nil
}

func buildTripPrompt(pair tripPair, promptType string) string {
	var promptInstruction string
	switch promptType {
	case "analogy":
		promptInstruction = "How is entity A structurally, functionally, or conceptually similar to entity B? What shared pattern connects them despite belonging to different domains?"
	case "contradiction":
		promptInstruction = "How might entity A's claims undermine, challenge, or contradict entity B's claims? What tension exists between them?"
	case "genealogy":
		promptInstruction = "Could entity A have historically influenced entity B, or vice versa? Is there a causal, intellectual, or genealogical link?"
	case "prediction":
		promptInstruction = "If entity A's claims are true, what does that specifically imply for entity B? Generate a falsifiable prediction."
	}

	briefA := pair.A.brief
	if briefA == "" {
		briefA = "(no description available)"
	}
	briefB := pair.B.brief
	if briefB == "" {
		briefB = "(no description available)"
	}

	return fmt.Sprintf(`You are generating speculative cross-domain connections for a knowledge base about the epistemology of minds — how minds build, validate, and fail at modeling reality.

These two entities are in DIFFERENT clusters (no existing connection). Your job: find a non-obvious but defensible connection.

Entity A: %s (%s)
  %s

Entity B: %s (%s)
  %s

Connection type: %s
%s

Respond in this exact format:
CONNECTION: <one sentence describing the speculative connection>
PREDICATE: <which KB predicate type fits: InfluencedBy, DerivedFrom, Disputes, TheoryOf, CommentaryOn, or NONE if no existing predicate fits>
SCORE: <1-5 interestingness: 1=trivial, 2=weak, 3=interesting, 4=novel+defensible, 5=genuinely surprising>
RATIONALE: <one sentence explaining why this score>

If no meaningful connection exists, give SCORE: 1 and say so.`,
		pair.A.name, pair.A.roleType, briefA,
		pair.B.name, pair.B.roleType, briefB,
		promptType, promptInstruction)
}

func parseTripResponse(response string) TripConnection {
	var conn TripConnection
	for _, line := range strings.Split(response, "\n") {
		line = strings.TrimSpace(line)
		if v, ok := strings.CutPrefix(line, "CONNECTION:"); ok {
			conn.Connection = strings.TrimSpace(v)
		} else if v, ok := strings.CutPrefix(line, "PREDICATE:"); ok {
			pred := strings.TrimSpace(v)
			if pred != "NONE" && pred != "" {
				conn.Predicate = pred
			}
		} else if v, ok := strings.CutPrefix(line, "SCORE:"); ok {
			v = strings.TrimSpace(v)
			if n, err := strconv.Atoi(v); err == nil {
				if n < 1 {
					n = 1
				} else if n > 5 {
					n = 5
				}
				conn.Score = n
			} else {
				fmt.Fprintf(os.Stderr, "trip: score parse error %q: %v (defaulting to 1)\n", v, err)
			}
		} else if v, ok := strings.CutPrefix(line, "RATIONALE:"); ok {
			conn.Rationale = strings.TrimSpace(v)
		}
	}
	if conn.Score == 0 {
		conn.Score = 1 // default to lowest if parsing failed
	}
	return conn
}

// drugProfile characterizes the temperature × prompt combination.
func drugProfile(temperature float64, promptType string) string {
	var tempLabel string
	switch {
	case temperature >= 1.2:
		tempLabel = "psychedelic"
	case temperature >= 0.8:
		tempLabel = "exploratory"
	case temperature >= 0.4:
		tempLabel = "microdose"
	default:
		tempLabel = "sober"
	}

	var promptLabel string
	switch promptType {
	case "analogy":
		promptLabel = "pattern-matching"
	case "contradiction":
		promptLabel = "adversarial"
	case "genealogy":
		promptLabel = "causal-tracing"
	case "prediction":
		promptLabel = "forecasting"
	}

	return tempLabel + "/" + promptLabel
}
